/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.donor_management;

import controller.donor_management.DonorController;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Donor;

/**
 *
 * @author Upekka
 */
public class DeleteDonorForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormFilledByDonor
     */
    public DeleteDonorForm() throws IOException {
        try {
            initComponents();
            FileInputStream imgStream = null;
            File imgfile = new File("..\\BBMS\\src\\images\\drop.png");
            imgStream = new FileInputStream(imgfile);
            BufferedImage bi = ImageIO.read(imgStream);
            ImageIcon myImg = new ImageIcon(bi);
            this.setFrameIcon(myImg);
            setTitle("Delete Donor Form");
            ResultSet rst = DonorController.getListOfNic();
            while (rst.next()) {
                String nic = rst.getString("nic");
                if (nic.charAt(nic.length() - 1) == 'V' || nic.charAt(nic.length() - 1) == 'v') {
                    nicComboBox.addItem(nic);
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeleteDonorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteDonorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previouslyDonatedbuttonGroup = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        usingMedicinebuttonGroup = new javax.swing.ButtonGroup();
        surgeriesbuttonGroup = new javax.swing.ButtonGroup();
        heavyWorkbuttonGroup = new javax.swing.ButtonGroup();
        pregnantLactationAbortionbuttonGroup = new javax.swing.ButtonGroup();
        immunizedbuttonGroup = new javax.swing.ButtonGroup();
        piercedTatooedbuttonGroup = new javax.swing.ButtonGroup();
        imprisonedbuttonGroup = new javax.swing.ButtonGroup();
        youOrSpouceGoneAbroadbuttonGroup = new javax.swing.ButtonGroup();
        youOrSpouceTakenBloodbuttonGroup = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        genderButtonGroup = new javax.swing.ButtonGroup();
        goodHealthRadioButtonbuttonGroup = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        homeAddressTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        officeAddressTextField = new javax.swing.JTextField();
        homeTpTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        officeTpTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mobileTPTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dobDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        nicComboBox = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        previouslyDonatedRadioButton = new javax.swing.JRadioButton();
        notpreviouslyDonatedRadioButton = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        heartDiseaseCheckBox = new javax.swing.JCheckBox();
        fitsCheckBox = new javax.swing.JCheckBox();
        diabetiesCheckBox = new javax.swing.JCheckBox();
        paralysisCheckBox = new javax.swing.JCheckBox();
        asthmaLundCancerCheckBox = new javax.swing.JCheckBox();
        liverDiseaseCheckBox = new javax.swing.JCheckBox();
        kidneyDiseaseCheckBox = new javax.swing.JCheckBox();
        bloodDiseasesCheckBox = new javax.swing.JCheckBox();
        cancerCheckBox = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        usingMedicineRadioButton = new javax.swing.JRadioButton();
        notusingMedicineRadioButton = new javax.swing.JRadioButton();
        surgeriesRadioButton = new javax.swing.JRadioButton();
        nosurgeriesRadioButton = new javax.swing.JRadioButton();
        heavyWorkRadioButton = new javax.swing.JRadioButton();
        noheavyWorkRadioButton = new javax.swing.JRadioButton();
        pregnantLactationAbortionRadioButton = new javax.swing.JRadioButton();
        nopregnantLactationAbortionRadioButton = new javax.swing.JRadioButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        immunizedRadioButton = new javax.swing.JRadioButton();
        noimmunizedRadioButton = new javax.swing.JRadioButton();
        imprisonedRadioButton = new javax.swing.JRadioButton();
        noimprisonedRadioButton = new javax.swing.JRadioButton();
        youOrSpouceTakenBloodRadioButton = new javax.swing.JRadioButton();
        noyouOrSpouceTakenBloodRadioButton = new javax.swing.JRadioButton();
        piercedTatooedRadioButton = new javax.swing.JRadioButton();
        nopiercedTatooedRadioButton = new javax.swing.JRadioButton();
        youOrSpouceGoneAbroadRadioButton = new javax.swing.JRadioButton();
        noyouOrSpouceGoneAbroadRadioButton = new javax.swing.JRadioButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        sufferedFromYelowFeverHepatitisRadioButton = new javax.swing.JRadioButton();
        nosufferedFromYelowFeverHepatitisRadioButton = new javax.swing.JRadioButton();
        sufferedFromTuberculosisRadioButton = new javax.swing.JRadioButton();
        nosufferedFromTuberculosisRadioButton = new javax.swing.JRadioButton();
        sufferedFromMalariaRadioButton = new javax.swing.JRadioButton();
        nosufferedFromMalariaRadioButton = new javax.swing.JRadioButton();
        sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton = new javax.swing.JRadioButton();
        nosufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton = new javax.swing.JRadioButton();
        dentalSurgeryUsedAntibioticsMedicineRadioButton = new javax.swing.JRadioButton();
        nodentalSurgeryUsedAntibioticsMedicineRadioButton = new javax.swing.JRadioButton();
        difficultiesTextField = new javax.swing.JTextField();
        goodHealthRadioButton = new javax.swing.JRadioButton();
        nogoodHealthRadioButton = new javax.swing.JRadioButton();

        jPanel6.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Blood Donor's Statement and Report");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(298, 20, 360, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormHeader.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel6.add(jLabel2);
        jLabel2.setBounds(0, 0, 940, 73);

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_Icon1.png"))); // NOI18N
        updateButton.setText("Delete");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CloseButton2.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabel3.setText("Name:");

        nameTextField.setEnabled(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        maleRadioButton.setText("Male");
        maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonActionPerformed(evt);
            }
        });

        femaleRadioButton.setText("Female");
        femaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("NIC No:");

        jLabel6.setText("Date of Birth:");

        jLabel7.setText("Age:");

        ageTextField.setEnabled(false);
        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });
        ageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageTextFieldKeyTyped(evt);
            }
        });

        homeAddressTextField.setEnabled(false);

        jLabel8.setText("Official Address:");

        officeAddressTextField.setEnabled(false);

        homeTpTextField.setEnabled(false);
        homeTpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeTpTextFieldActionPerformed(evt);
            }
        });
        homeTpTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homeTpTextFieldKeyTyped(evt);
            }
        });

        jLabel9.setText("Home:");

        jLabel10.setText("Telephone no:");

        jLabel11.setText("Office:");

        officeTpTextField.setEnabled(false);
        officeTpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officeTpTextFieldActionPerformed(evt);
            }
        });
        officeTpTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                officeTpTextFieldKeyTyped(evt);
            }
        });

        jLabel12.setText("Mobile:");

        mobileTPTextField.setEnabled(false);
        mobileTPTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileTPTextFieldKeyTyped(evt);
            }
        });

        emailTextField.setEnabled(false);

        jLabel13.setText("e-mail:");

        jLabel14.setText("Home Address:");

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Details of the Blood Donor");

        dobDateChooser.setEnabled(false);

        jLabel16.setText("Weight (kg):");

        weightTextField.setEnabled(false);
        weightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTextFieldActionPerformed(evt);
            }
        });
        weightTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weightTextFieldKeyTyped(evt);
            }
        });

        nicComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select NIC" }));
        nicComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicComboBoxActionPerformed(evt);
            }
        });

        jLabel17.setText("Gender:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addGap(50, 50, 50)
                                .addComponent(emailTextField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel16)
                                        .addGap(29, 29, 29)
                                        .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(homeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(femaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 11, Short.MAX_VALUE)))
                        .addGap(456, 456, 456))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(homeTpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(officeTpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addGap(14, 14, 14)
                                        .addComponent(mobileTPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(officeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(nicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(dobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(officeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(homeTpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(officeTpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileTPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel1);

        jScrollPane2.setViewportView(jScrollPane3);

        jTabbedPane1.addTab("Donor Details", jScrollPane2);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel19.setText("a. Has donated blood ever before?");

        jLabel22.setText("b. Difficulties happened in prevoius donations?");

        jLabel26.setText("(1)");

        previouslyDonatedRadioButton.setText("yes");
        previouslyDonatedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previouslyDonatedRadioButtonActionPerformed(evt);
            }
        });

        notpreviouslyDonatedRadioButton.setText("no");

        jLabel27.setText("(2) a. Is in good health state now?");

        jLabel28.setText("b. Has suffered from or got treatment for the following diseases?  ");

        heartDiseaseCheckBox.setText("Heart diseases");
        heartDiseaseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartDiseaseCheckBoxActionPerformed(evt);
            }
        });

        fitsCheckBox.setText("Fits");
        fitsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitsCheckBoxActionPerformed(evt);
            }
        });

        diabetiesCheckBox.setText("Diabetes");
        diabetiesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diabetiesCheckBoxActionPerformed(evt);
            }
        });

        paralysisCheckBox.setText("Paralysis");
        paralysisCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paralysisCheckBoxActionPerformed(evt);
            }
        });

        asthmaLundCancerCheckBox.setText("Asthma/ lung diseases");
        asthmaLundCancerCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asthmaLundCancerCheckBoxActionPerformed(evt);
            }
        });

        liverDiseaseCheckBox.setText("Liver diseases");
        liverDiseaseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liverDiseaseCheckBoxActionPerformed(evt);
            }
        });

        kidneyDiseaseCheckBox.setText("Kidney diseases");
        kidneyDiseaseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidneyDiseaseCheckBoxActionPerformed(evt);
            }
        });

        bloodDiseasesCheckBox.setText("Blood diseases");
        bloodDiseasesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodDiseasesCheckBoxActionPerformed(evt);
            }
        });

        cancerCheckBox.setText("Cancers");
        cancerCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancerCheckBoxActionPerformed(evt);
            }
        });

        jLabel29.setText("c. Is currently using any medicine/teatment?");

        jLabel30.setText("d. Has faced any surgery? ");

        jLabel31.setText("e. Has to engage in heavy work, drive passenger vehicles, work on a high building or ");

        jLabel32.setText("operate large machines after donating blood");

        jLabel33.setText("f. Is pregnent? doing lactation? Has faced a delivery or abortion during the last 12 months?");

        usingMedicineRadioButton.setText("yes");
        usingMedicineRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usingMedicineRadioButtonActionPerformed(evt);
            }
        });

        notusingMedicineRadioButton.setText("no");

        surgeriesRadioButton.setText("yes");
        surgeriesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeriesRadioButtonActionPerformed(evt);
            }
        });

        nosurgeriesRadioButton.setText("no");

        heavyWorkRadioButton.setText("yes");
        heavyWorkRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heavyWorkRadioButtonActionPerformed(evt);
            }
        });

        noheavyWorkRadioButton.setText("no");

        pregnantLactationAbortionRadioButton.setText("yes");
        pregnantLactationAbortionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregnantLactationAbortionRadioButtonActionPerformed(evt);
            }
        });

        nopregnantLactationAbortionRadioButton.setText("no");

        jLabel34.setText("(3) During the past 12 months,");

        jLabel35.setText("a. Has taken an immunization or another vaccine");

        jLabel36.setText("b. Has done any piercing,tatooing or acupuncture treatment?");

        jLabel37.setText("c. Has been imprisoned?");

        jLabel38.setText("d. Have you or your spouse gone abroad? ");

        jLabel39.setText("e.Has the donor or his/her spouse taken blood or blood components?");

        jLabel40.setText("(4) a.Has ever suffered from yellow fever/hepatitis?");

        immunizedRadioButton.setText("yes");
        immunizedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                immunizedRadioButtonActionPerformed(evt);
            }
        });

        noimmunizedRadioButton.setText("no");

        imprisonedRadioButton.setText("yes");
        imprisonedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprisonedRadioButtonActionPerformed(evt);
            }
        });

        noimprisonedRadioButton.setText("no");

        youOrSpouceTakenBloodRadioButton.setText("yes");
        youOrSpouceTakenBloodRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youOrSpouceTakenBloodRadioButtonActionPerformed(evt);
            }
        });

        noyouOrSpouceTakenBloodRadioButton.setText("no");

        piercedTatooedRadioButton.setText("yes");
        piercedTatooedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piercedTatooedRadioButtonActionPerformed(evt);
            }
        });

        nopiercedTatooedRadioButton.setText("no");

        youOrSpouceGoneAbroadRadioButton.setText("yes");
        youOrSpouceGoneAbroadRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youOrSpouceGoneAbroadRadioButtonActionPerformed(evt);
            }
        });

        noyouOrSpouceGoneAbroadRadioButton.setText("no");

        jLabel41.setText("b.Has suffered from tuberculosis/typhoid during the last 2 years? Has taken treatment?");

        jLabel42.setText("b.Has suffered from Malaria during the last 3 months? ");

        jLabel43.setText("c. Has suffered from Chicken Pox,measles,rubella(german measles),diarrhea,dengue,");

        jLabel44.setText(" or suffered from  any fever (for more than one week) during the last month");

        jLabel45.setText("d. Has done a dental surgery? Use any Antibiotics  ,  ");

        jLabel46.setText(" Asprin or any medicine during the last week");

        sufferedFromYelowFeverHepatitisRadioButton.setText("yes");
        sufferedFromYelowFeverHepatitisRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sufferedFromYelowFeverHepatitisRadioButtonActionPerformed(evt);
            }
        });

        nosufferedFromYelowFeverHepatitisRadioButton.setText("no");

        sufferedFromTuberculosisRadioButton.setText("yes");
        sufferedFromTuberculosisRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sufferedFromTuberculosisRadioButtonActionPerformed(evt);
            }
        });

        nosufferedFromTuberculosisRadioButton.setText("no");

        sufferedFromMalariaRadioButton.setText("yes");
        sufferedFromMalariaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sufferedFromMalariaRadioButtonActionPerformed(evt);
            }
        });

        nosufferedFromMalariaRadioButton.setText("no");

        sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton.setText("yes");
        sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButtonActionPerformed(evt);
            }
        });

        nosufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton.setText("no");

        dentalSurgeryUsedAntibioticsMedicineRadioButton.setText("yes");
        dentalSurgeryUsedAntibioticsMedicineRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dentalSurgeryUsedAntibioticsMedicineRadioButtonActionPerformed(evt);
            }
        });

        nodentalSurgeryUsedAntibioticsMedicineRadioButton.setText("no");

        goodHealthRadioButton.setText("yes");
        goodHealthRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodHealthRadioButtonActionPerformed(evt);
            }
        });

        nogoodHealthRadioButton.setText("no");
        nogoodHealthRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nogoodHealthRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel32)))
                        .addGap(0, 672, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(youOrSpouceTakenBloodRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(noyouOrSpouceTakenBloodRadioButton))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(imprisonedRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(noimprisonedRadioButton))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(piercedTatooedRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(nopiercedTatooedRadioButton)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(youOrSpouceGoneAbroadRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(noyouOrSpouceGoneAbroadRadioButton))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(immunizedRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(noimmunizedRadioButton))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(goodHealthRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nogoodHealthRadioButton))
                                            .addComponent(jLabel28))
                                        .addGap(80, 80, 80))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(surgeriesRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nosurgeriesRadioButton))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(heavyWorkRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(noheavyWorkRadioButton))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(usingMedicineRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(notusingMedicineRadioButton))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(pregnantLactationAbortionRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nopregnantLactationAbortionRadioButton))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cancerCheckBox)
                                            .addComponent(liverDiseaseCheckBox)
                                            .addComponent(fitsCheckBox))
                                        .addGap(39, 39, 39)))
                                .addGap(3, 3, 3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paralysisCheckBox)
                                    .addComponent(heartDiseaseCheckBox)
                                    .addComponent(kidneyDiseaseCheckBox))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bloodDiseasesCheckBox)
                                    .addComponent(diabetiesCheckBox)
                                    .addComponent(asthmaLundCancerCheckBox))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel40)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel38)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel46)))
                            .addComponent(jLabel45))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nosufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sufferedFromMalariaRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nosufferedFromMalariaRadioButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sufferedFromTuberculosisRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nosufferedFromTuberculosisRadioButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dentalSurgeryUsedAntibioticsMedicineRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nodentalSurgeryUsedAntibioticsMedicineRadioButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sufferedFromYelowFeverHepatitisRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nosufferedFromYelowFeverHepatitisRadioButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(difficultiesTextField))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(106, 106, 106)
                                        .addComponent(previouslyDonatedRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(notpreviouslyDonatedRadioButton)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(158, 158, 158))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(difficultiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(goodHealthRadioButton)
                                    .addComponent(nogoodHealthRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(heartDiseaseCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(paralysisCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(kidneyDiseaseCheckBox))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(diabetiesCheckBox)
                                            .addComponent(fitsCheckBox, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(asthmaLundCancerCheckBox)
                                            .addComponent(liverDiseaseCheckBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bloodDiseasesCheckBox)
                                            .addComponent(cancerCheckBox)))))
                            .addComponent(notpreviouslyDonatedRadioButton)
                            .addComponent(previouslyDonatedRadioButton))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nopregnantLactationAbortionRadioButton)
                                .addComponent(pregnantLactationAbortionRadioButton))
                            .addComponent(jLabel33)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notusingMedicineRadioButton)
                            .addComponent(usingMedicineRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nosurgeriesRadioButton)
                            .addComponent(surgeriesRadioButton))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noheavyWorkRadioButton)
                            .addComponent(heavyWorkRadioButton))
                        .addGap(35, 35, 35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(noimmunizedRadioButton)
                        .addComponent(immunizedRadioButton)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel36))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nopiercedTatooedRadioButton)
                                                    .addComponent(piercedTatooedRadioButton))))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel37)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(noimprisonedRadioButton)
                                                .addComponent(imprisonedRadioButton)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel38))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(noyouOrSpouceGoneAbroadRadioButton)
                                                    .addComponent(youOrSpouceGoneAbroadRadioButton))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel39)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(noyouOrSpouceTakenBloodRadioButton)
                                                .addComponent(youOrSpouceTakenBloodRadioButton)))
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel40))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(154, 154, 154)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nosufferedFromYelowFeverHepatitisRadioButton)
                                            .addComponent(sufferedFromYelowFeverHepatitisRadioButton))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nosufferedFromTuberculosisRadioButton)
                                        .addComponent(sufferedFromTuberculosisRadioButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42)
                                    .addComponent(nosufferedFromMalariaRadioButton)
                                    .addComponent(sufferedFromMalariaRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nosufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton)
                                .addComponent(sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nodentalSurgeryUsedAntibioticsMedicineRadioButton)
                        .addComponent(dentalSurgeryUsedAntibioticsMedicineRadioButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPane1.addTab("Questionnaire", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(101, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(532, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        try {

            String nic = "";
            nic = (String) nicComboBox.getSelectedItem();
            int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Are you sure that you want to delete Donor " + nic);
            if (showConfirmDialog == 0) {
                int deleted = DonorController.deleteDonor(nic);
                if (deleted == 1) {
                    JOptionPane.showMessageDialog(null, "Deleted Succesfully");
                    clearAllFields();
                } else {
                    JOptionPane.showMessageDialog(null, "Error while Deleting!");
                    clearAllFields();
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeleteDonorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteDonorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Are you sure that you want to exit ?");
        System.out.println(showConfirmDialog);
        if (showConfirmDialog == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioButtonActionPerformed

    private void femaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioButtonActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void ageTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextFieldKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE) || c == java.awt.event.KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_ageTextFieldKeyTyped

    private void homeTpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeTpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeTpTextFieldActionPerformed

    private void homeTpTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeTpTextFieldKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE) || c == java.awt.event.KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_homeTpTextFieldKeyTyped

    private void officeTpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officeTpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officeTpTextFieldActionPerformed

    private void officeTpTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_officeTpTextFieldKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE) || c == java.awt.event.KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_officeTpTextFieldKeyTyped

    private void mobileTPTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileTPTextFieldKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE) || c == java.awt.event.KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_mobileTPTextFieldKeyTyped

    private void weightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTextFieldActionPerformed

    private void weightTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weightTextFieldKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE) || c == java.awt.event.KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_weightTextFieldKeyTyped

    private void nicComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicComboBoxActionPerformed
        try {
            searchDonorbyNic((String) nicComboBox.getSelectedItem());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeleteDonorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteDonorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nicComboBoxActionPerformed

    private void previouslyDonatedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previouslyDonatedRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previouslyDonatedRadioButtonActionPerformed

    private void heartDiseaseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartDiseaseCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartDiseaseCheckBoxActionPerformed

    private void fitsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitsCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fitsCheckBoxActionPerformed

    private void diabetiesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diabetiesCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diabetiesCheckBoxActionPerformed

    private void paralysisCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paralysisCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paralysisCheckBoxActionPerformed

    private void asthmaLundCancerCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asthmaLundCancerCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asthmaLundCancerCheckBoxActionPerformed

    private void liverDiseaseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liverDiseaseCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liverDiseaseCheckBoxActionPerformed

    private void kidneyDiseaseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidneyDiseaseCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kidneyDiseaseCheckBoxActionPerformed

    private void bloodDiseasesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodDiseasesCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodDiseasesCheckBoxActionPerformed

    private void cancerCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancerCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancerCheckBoxActionPerformed

    private void usingMedicineRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usingMedicineRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usingMedicineRadioButtonActionPerformed

    private void surgeriesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeriesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgeriesRadioButtonActionPerformed

    private void heavyWorkRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heavyWorkRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heavyWorkRadioButtonActionPerformed

    private void pregnantLactationAbortionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregnantLactationAbortionRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pregnantLactationAbortionRadioButtonActionPerformed

    private void immunizedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_immunizedRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_immunizedRadioButtonActionPerformed

    private void imprisonedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprisonedRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprisonedRadioButtonActionPerformed

    private void youOrSpouceTakenBloodRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youOrSpouceTakenBloodRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_youOrSpouceTakenBloodRadioButtonActionPerformed

    private void piercedTatooedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piercedTatooedRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piercedTatooedRadioButtonActionPerformed

    private void youOrSpouceGoneAbroadRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youOrSpouceGoneAbroadRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_youOrSpouceGoneAbroadRadioButtonActionPerformed

    private void sufferedFromYelowFeverHepatitisRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sufferedFromYelowFeverHepatitisRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sufferedFromYelowFeverHepatitisRadioButtonActionPerformed

    private void sufferedFromTuberculosisRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sufferedFromTuberculosisRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sufferedFromTuberculosisRadioButtonActionPerformed

    private void sufferedFromMalariaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sufferedFromMalariaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sufferedFromMalariaRadioButtonActionPerformed

    private void sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButtonActionPerformed

    private void dentalSurgeryUsedAntibioticsMedicineRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dentalSurgeryUsedAntibioticsMedicineRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dentalSurgeryUsedAntibioticsMedicineRadioButtonActionPerformed

    private void goodHealthRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodHealthRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goodHealthRadioButtonActionPerformed

    private void nogoodHealthRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nogoodHealthRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nogoodHealthRadioButtonActionPerformed

    private void searchDonorbyNic(String nic) throws ClassNotFoundException, SQLException {

        Donor existingDonor = DonorController.searchDonor(nic);
        if (existingDonor != null) {
            nameTextField.setText(existingDonor.getName());
            if (existingDonor.getGender().equals("male")) {
                maleRadioButton.setSelected(true);
            } else {
                femaleRadioButton.setSelected(true);
            }
            dobDateChooser.setDate(existingDonor.getDob());
            ageTextField.setText(Integer.toString(existingDonor.getAge()));
            weightTextField.setText(Integer.toString(existingDonor.getWeight()));
            homeAddressTextField.setText(existingDonor.getHomeAddress());
            officeAddressTextField.setText(existingDonor.getOfficeAddress());
            homeTpTextField.setText(Integer.toString(existingDonor.getHomeTp()));
            officeTpTextField.setText(Integer.toString(existingDonor.getOfficeTp()));
            mobileTPTextField.setText(Integer.toString(existingDonor.getMobileTp()));
            emailTextField.setText(existingDonor.getEmail());

            if (existingDonor.getPreviouslyDonated() == 1) {
                previouslyDonatedRadioButton.setSelected(true);
            } else {
                notpreviouslyDonatedRadioButton.setSelected(true);
            }
            difficultiesTextField.setText(existingDonor.getDifficultiesAfterDonation());

            if (existingDonor.getGoodHealth() == 1) {
                goodHealthRadioButton.setSelected(true);
            } else {
                nogoodHealthRadioButton.setSelected(true);
            }
            if (existingDonor.getDiseases().contains("Heart diseases")) {
                heartDiseaseCheckBox.setSelected(true);
            }
            if (existingDonor.getDiseases().contains("Diabetes")) {
                diabetiesCheckBox.setSelected(true);
            }
            if (existingDonor.getDiseases().contains("Fits")) {
                fitsCheckBox.setSelected(true);
            }
            if (existingDonor.getDiseases().contains("Paralysis")) {
                paralysisCheckBox.setSelected(true);
            }
            if (existingDonor.getDiseases().contains("Asthma/ lung diseases")) {
                asthmaLundCancerCheckBox.setSelected(true);
            }
            if (existingDonor.getDiseases().contains("Liver diseases")) {
                liverDiseaseCheckBox.setSelected(true);
            }
            if (existingDonor.getDiseases().contains("Kidney diseases")) {
                kidneyDiseaseCheckBox.setSelected(true);
            }
            if (existingDonor.getDiseases().contains("Blood diseases")) {
                bloodDiseasesCheckBox.setSelected(true);
            }
            if (existingDonor.getDiseases().contains("Cancers")) {
                cancerCheckBox.setSelected(true);
            }

            if (existingDonor.getUsingMedicine() == 1) {
                usingMedicineRadioButton.setSelected(true);
            } else {
                notusingMedicineRadioButton.setSelected(true);
            }
            if (existingDonor.getSurgeries() == 1) {
                surgeriesRadioButton.setSelected(true);
            } else {
                nosurgeriesRadioButton.setSelected(true);
            }
            if (existingDonor.getHeavyWork() == 1) {
                heavyWorkRadioButton.setSelected(true);
            } else {
                noheavyWorkRadioButton.setSelected(true);
            }
            if (existingDonor.getPregnantLactationAbortion() == 1) {
                pregnantLactationAbortionRadioButton.setSelected(true);
            } else {
                nopregnantLactationAbortionRadioButton.setSelected(true);
            }
            if (existingDonor.getImmunized() == 1) {
                immunizedRadioButton.setSelected(true);
            } else {
                noimmunizedRadioButton.setSelected(true);
            }

            if (existingDonor.getPiercedTatooed() == 1) {
                piercedTatooedRadioButton.setSelected(true);
            } else {
                nopiercedTatooedRadioButton.setSelected(true);
            }

            if (existingDonor.getImprisone() == 1) {
                imprisonedRadioButton.setSelected(true);
            } else {
                noimprisonedRadioButton.setSelected(true);
            }
            if (existingDonor.getYouOrSpouceGoneAbroad() == 1) {
                youOrSpouceGoneAbroadRadioButton.setSelected(true);
            } else {
                noyouOrSpouceGoneAbroadRadioButton.setSelected(true);
            }
            if (existingDonor.getYouOrSpouceTakenBlood() == 1) {
                youOrSpouceTakenBloodRadioButton.setSelected(true);
            } else {
                noyouOrSpouceTakenBloodRadioButton.setSelected(true);
            }
            if (existingDonor.getSufferedFromYelowFeverHepatitis() == 1) {
                sufferedFromYelowFeverHepatitisRadioButton.setSelected(true);
            } else {
                nosufferedFromYelowFeverHepatitisRadioButton.setSelected(true);
            }
            if (existingDonor.getSufferedFromTuberculosis() == 1) {
                sufferedFromTuberculosisRadioButton.setSelected(true);
            } else {
                nosufferedFromTuberculosisRadioButton.setSelected(true);
            }
            if (existingDonor.getSufferedFromMalaria() == 1) {
                sufferedFromMalariaRadioButton.setSelected(true);
            } else {
                nosufferedFromMalariaRadioButton.setSelected(true);
            }
            if (existingDonor.getSufferedFromChickenpoxMeaselsRubellaDiarrheaDengue() == 1) {
                sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton.setSelected(true);
            } else {
                nosufferedFromMalariaRadioButton.setSelected(true);
            }
            if (existingDonor.getDentalSurgeryUsedAntibioticsMedicine() == 1) {
                dentalSurgeryUsedAntibioticsMedicineRadioButton.setSelected(true);
            } else {
                nodentalSurgeryUsedAntibioticsMedicineRadioButton.setSelected(true);
            }

        } else {
            JOptionPane.showMessageDialog(this, "No such donor found... Please enter the NIC number correctly.");
        }
    }

    private void clearAllFields() {

        nameTextField.setText("");
        //nicComboBox.setSelectedIndex(0);
        genderButtonGroup.clearSelection();
        dobDateChooser.setDate(null);
        ageTextField.setText(null);
        weightTextField.setText(null);
        homeAddressTextField.setText("");
        officeAddressTextField.setText("");
        homeTpTextField.setText(null);
        officeTpTextField.setText(null);
        mobileTPTextField.setText(null);
        emailTextField.setText("");

        previouslyDonatedbuttonGroup.clearSelection();
        difficultiesTextField.setText("");
        goodHealthRadioButtonbuttonGroup.clearSelection();

        heartDiseaseCheckBox.setSelected(false);
        diabetiesCheckBox.setSelected(false);
        fitsCheckBox.setSelected(false);
        paralysisCheckBox.setSelected(false);
        asthmaLundCancerCheckBox.setSelected(false);
        liverDiseaseCheckBox.setSelected(false);
        kidneyDiseaseCheckBox.setSelected(false);
        bloodDiseasesCheckBox.setSelected(false);
        cancerCheckBox.setSelected(false);

        usingMedicinebuttonGroup.clearSelection();
        surgeriesbuttonGroup.clearSelection();
        heavyWorkbuttonGroup.clearSelection();
        pregnantLactationAbortionbuttonGroup.clearSelection();
        immunizedbuttonGroup.clearSelection();
        piercedTatooedbuttonGroup.clearSelection();
        imprisonedbuttonGroup.clearSelection();
        youOrSpouceGoneAbroadbuttonGroup.clearSelection();
        youOrSpouceTakenBloodbuttonGroup.clearSelection();
        buttonGroup14.clearSelection();
        buttonGroup15.clearSelection();
        buttonGroup16.clearSelection();
        buttonGroup17.clearSelection();
        buttonGroup18.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JCheckBox asthmaLundCancerCheckBox;
    private javax.swing.JCheckBox bloodDiseasesCheckBox;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox cancerCheckBox;
    private javax.swing.JRadioButton dentalSurgeryUsedAntibioticsMedicineRadioButton;
    private javax.swing.JCheckBox diabetiesCheckBox;
    private javax.swing.JTextField difficultiesTextField;
    private com.toedter.calendar.JDateChooser dobDateChooser;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JCheckBox fitsCheckBox;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JRadioButton goodHealthRadioButton;
    private javax.swing.ButtonGroup goodHealthRadioButtonbuttonGroup;
    private javax.swing.JCheckBox heartDiseaseCheckBox;
    private javax.swing.JRadioButton heavyWorkRadioButton;
    private javax.swing.ButtonGroup heavyWorkbuttonGroup;
    private javax.swing.JTextField homeAddressTextField;
    private javax.swing.JTextField homeTpTextField;
    private javax.swing.JRadioButton immunizedRadioButton;
    private javax.swing.ButtonGroup immunizedbuttonGroup;
    private javax.swing.JRadioButton imprisonedRadioButton;
    private javax.swing.ButtonGroup imprisonedbuttonGroup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox kidneyDiseaseCheckBox;
    private javax.swing.JCheckBox liverDiseaseCheckBox;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField mobileTPTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox nicComboBox;
    private javax.swing.JRadioButton nodentalSurgeryUsedAntibioticsMedicineRadioButton;
    private javax.swing.JRadioButton nogoodHealthRadioButton;
    private javax.swing.JRadioButton noheavyWorkRadioButton;
    private javax.swing.JRadioButton noimmunizedRadioButton;
    private javax.swing.JRadioButton noimprisonedRadioButton;
    private javax.swing.JRadioButton nopiercedTatooedRadioButton;
    private javax.swing.JRadioButton nopregnantLactationAbortionRadioButton;
    private javax.swing.JRadioButton nosufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton;
    private javax.swing.JRadioButton nosufferedFromMalariaRadioButton;
    private javax.swing.JRadioButton nosufferedFromTuberculosisRadioButton;
    private javax.swing.JRadioButton nosufferedFromYelowFeverHepatitisRadioButton;
    private javax.swing.JRadioButton nosurgeriesRadioButton;
    private javax.swing.JRadioButton notpreviouslyDonatedRadioButton;
    private javax.swing.JRadioButton notusingMedicineRadioButton;
    private javax.swing.JRadioButton noyouOrSpouceGoneAbroadRadioButton;
    private javax.swing.JRadioButton noyouOrSpouceTakenBloodRadioButton;
    private javax.swing.JTextField officeAddressTextField;
    private javax.swing.JTextField officeTpTextField;
    private javax.swing.JCheckBox paralysisCheckBox;
    private javax.swing.JRadioButton piercedTatooedRadioButton;
    private javax.swing.ButtonGroup piercedTatooedbuttonGroup;
    private javax.swing.JRadioButton pregnantLactationAbortionRadioButton;
    private javax.swing.ButtonGroup pregnantLactationAbortionbuttonGroup;
    private javax.swing.JRadioButton previouslyDonatedRadioButton;
    private javax.swing.ButtonGroup previouslyDonatedbuttonGroup;
    private javax.swing.JRadioButton sufferedFromChickenpoxMeaselsRubellaDiarrheaDengueRadioButton;
    private javax.swing.JRadioButton sufferedFromMalariaRadioButton;
    private javax.swing.JRadioButton sufferedFromTuberculosisRadioButton;
    private javax.swing.JRadioButton sufferedFromYelowFeverHepatitisRadioButton;
    private javax.swing.JRadioButton surgeriesRadioButton;
    private javax.swing.ButtonGroup surgeriesbuttonGroup;
    private javax.swing.JButton updateButton;
    private javax.swing.JRadioButton usingMedicineRadioButton;
    private javax.swing.ButtonGroup usingMedicinebuttonGroup;
    private javax.swing.JTextField weightTextField;
    private javax.swing.JRadioButton youOrSpouceGoneAbroadRadioButton;
    private javax.swing.ButtonGroup youOrSpouceGoneAbroadbuttonGroup;
    private javax.swing.JRadioButton youOrSpouceTakenBloodRadioButton;
    private javax.swing.ButtonGroup youOrSpouceTakenBloodbuttonGroup;
    // End of variables declaration//GEN-END:variables

}
