/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Administrator.java
 *
 * Created on Aug 18, 2014, 1:55:47 PM
 */
package view.users;

import controller.blood_stock_management.BloodStockUpdateNotifier;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.blood_stock_management.AddBloodGroups;
import view.blood_stock_management.AddBloodTypes;
import view.blood_stock_management.AddRequestee;
import view.blood_stock_management.StockBalance;
import view.camp_management.MobileCampTables;
import view.common.ChangePassword;
import view.common.Initial;
import view.common.Login;
import view.donor_management.ViewDonorRegister;
import view.issueing.AddHospitalWard;
import view.issueing.IssueRegister;
import view.item_management.ItemManagement;
import view.statistics.BloodRecievalLog;
import view.statistics.DiscardedBlood;
import view.statistics.IssueChart;
import view.statistics.RequestStatsAndPrediction;
import view.testing.BloodAndComponentAvailability;
import view.testing.GroupingAndTTIRegister;

/**
 *
 * @author Anuradha
 */
public class Administrator extends javax.swing.JFrame {

    BloodStockUpdateNotifier notifier = null;

    boolean isBloodStockEntered;

    public JDesktopPane getDesktop() {
        return desktopPane;
    }

    /**
     * Creates new form Administrator
     */
    public Administrator() throws IOException {
        FileInputStream imgStream = null;
        try {
            initComponents();
            File imgfile = new File("..\\BBMS\\src\\images\\drop.png");
            imgStream = new FileInputStream(imgfile);
            BufferedImage bi = ImageIO.read(imgStream);
            ImageIcon myImg = new ImageIcon(bi);
            this.setIconImage(myImg.getImage());
            setTitle("Karapitiya Blood Bank Management System");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                imgStream.close();
            } catch (IOException ex) {
                Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Initial first = new Initial(desktopPane.getSize());
        desktopPane.removeAll();
        desktopPane.add(first);
        first.setVisible(true);

        currentDate();
    }

    public void currentDate() {

        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    date_txt.setText("Date " + year + "/" + (month + 1) + "/" + day);

                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    time_txt.setText("Time " + hour + ":" + (minute) + ":" + second);

                    try {
                        sleep(1000);
                    } catch (Exception e) {

                    }

                }
            }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        desktopPane = new javax.swing.JDesktopPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        ttiBtn = new javax.swing.JButton();
        bloodGroupBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        desktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        groupingAndTTIRegButton = new javax.swing.JButton();
        BloodGroupButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        testingButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        sampleDetailsButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        issueRegisterButton = new javax.swing.JButton();
        generateIssuesButton = new javax.swing.JButton();
        addSampleBtn = new javax.swing.JButton();
        issueBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        passwordBtn = new javax.swing.JButton();
        date_txt = new javax.swing.JTextField();
        time_txt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        requestsButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        testingButton1 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        groupingAndTTIRegButton1 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        groupingAndTTIRegButton2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton32 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1168, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        jLayeredPane1.add(desktopPane);
        desktopPane.setBounds(200, 60, 1170, 650);

        ttiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TTI test icon.png"))); // NOI18N
        ttiBtn.setToolTipText("Blood Types");
        ttiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttiBtnActionPerformed(evt);
            }
        });
        jLayeredPane2.add(ttiBtn);
        ttiBtn.setBounds(60, 0, 60, 60);

        bloodGroupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crossmatch.png"))); // NOI18N
        bloodGroupBtn.setToolTipText("Requestees");
        bloodGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupBtnActionPerformed(evt);
            }
        });
        jLayeredPane2.add(bloodGroupBtn);
        bloodGroupBtn.setBounds(120, 0, 60, 60);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Karapitiya Blood Bank Management System");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(370, 0, 710, 60);

        desktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        javax.swing.GroupLayout desktopPane1Layout = new javax.swing.GroupLayout(desktopPane1);
        desktopPane1.setLayout(desktopPane1Layout);
        desktopPane1Layout.setHorizontalGroup(
            desktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1148, Short.MAX_VALUE)
        );
        desktopPane1Layout.setVerticalGroup(
            desktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        jLayeredPane2.add(desktopPane1);
        desktopPane1.setBounds(200, 60, 1150, 650);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setFocusTraversalPolicyProvider(true);
        jPanel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        groupingAndTTIRegButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        groupingAndTTIRegButton.setText("TTI Register");
        groupingAndTTIRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupingAndTTIRegButtonActionPerformed(evt);
            }
        });

        BloodGroupButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        BloodGroupButton.setText("Blood Grouping and TTI");
        BloodGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodGroupButtonActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton5.setText("Delete/Update Test");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupingAndTTIRegButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BloodGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(groupingAndTTIRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BloodGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanel2);
        jPanel2.setBounds(0, 220, 200, 140);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton18.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton18.setText("Blood Stock");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton19.setText("Blood Categories");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        testingButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        testingButton.setText("Blood and Component Availability");
        testingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(testingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanel3);
        jPanel3.setBounds(0, 520, 200, 160);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton22.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton22.setText("View Requests");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        sampleDetailsButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        sampleDetailsButton.setText("Add Sample Details");
        sampleDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sampleDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sampleDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanel4);
        jPanel4.setBounds(0, 90, 200, 110);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Issues", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        issueRegisterButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        issueRegisterButton.setText("Issue Register");
        issueRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueRegisterButtonActionPerformed(evt);
            }
        });

        generateIssuesButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        generateIssuesButton.setText("Generate Issues");
        generateIssuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateIssuesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generateIssuesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(issueRegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generateIssuesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(issueRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jLayeredPane2.add(jPanel1);
        jPanel1.setBounds(0, 380, 147, 110);

        addSampleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addSample.png"))); // NOI18N
        addSampleBtn.setToolTipText("Blood Groups");
        addSampleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSampleBtnActionPerformed(evt);
            }
        });
        jLayeredPane2.add(addSampleBtn);
        addSampleBtn.setBounds(0, 0, 60, 60);

        issueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blood Issue.png"))); // NOI18N
        issueBtn.setToolTipText("Hospitals/Wards");
        issueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBtnActionPerformed(evt);
            }
        });
        jLayeredPane2.add(issueBtn);
        issueBtn.setBounds(180, 0, 60, 60);

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletetest.png"))); // NOI18N
        deleteBtn.setToolTipText("Logout");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jLayeredPane2.add(deleteBtn);
        deleteBtn.setBounds(1310, 0, 60, 60);

        passwordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        passwordBtn.setToolTipText("Change Password");
        passwordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordBtnActionPerformed(evt);
            }
        });
        jLayeredPane2.add(passwordBtn);
        passwordBtn.setBounds(1250, 0, 60, 60);

        date_txt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        date_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane2.add(date_txt);
        date_txt.setBounds(1130, 10, 110, 20);

        time_txt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        time_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        time_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time_txtActionPerformed(evt);
            }
        });
        jLayeredPane2.add(time_txt);
        time_txt.setBounds(1130, 40, 110, 20);

        jLayeredPane1.add(jLayeredPane2);
        jLayeredPane2.setBounds(-2, -1, 1370, 60);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Predictions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        requestsButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        requestsButton.setText("Blood Request Statistics");
        requestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(requestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(requestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel7);
        jPanel7.setBounds(0, 370, 202, 80);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton20.setBackground(new java.awt.Color(255, 0, 0));
        jButton20.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton20.setText("Blood Stock");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        testingButton1.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        testingButton1.setText("Availability");
        testingButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testingButton1ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(255, 0, 0));
        jButton25.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton25.setText("Donor Register");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        groupingAndTTIRegButton1.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        groupingAndTTIRegButton1.setText("TTI Register");
        groupingAndTTIRegButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupingAndTTIRegButton1ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 0, 0));
        jButton16.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton16.setText("Item Stock");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton17.setText("Recieved Blood Stock");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        groupingAndTTIRegButton2.setBackground(new java.awt.Color(255, 0, 0));
        groupingAndTTIRegButton2.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        groupingAndTTIRegButton2.setText("Discarded Blood Stock");
        groupingAndTTIRegButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupingAndTTIRegButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(testingButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(groupingAndTTIRegButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(groupingAndTTIRegButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testingButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupingAndTTIRegButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupingAndTTIRegButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPane1.add(jPanel8);
        jPanel8.setBounds(0, 80, 200, 290);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Campaigns", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel11.setFocusTraversalPolicyProvider(true);
        jPanel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton26.setBackground(new java.awt.Color(255, 0, 0));
        jButton26.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton26.setText("Blood Campaigns");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPane1.add(jPanel11);
        jPanel11.setBounds(0, 580, 200, 80);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blood Issue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel9.setFocusTraversalPolicyProvider(true);
        jPanel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton32.setBackground(new java.awt.Color(255, 0, 0));
        jButton32.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton32.setText("Daily Issue Register");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton1.setText("Issue Charts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel9);
        jPanel9.setBounds(0, 460, 202, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1371, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsButtonActionPerformed
        RequestStatsAndPrediction pred = null;
        try {
            pred = new RequestStatsAndPrediction();
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }
        pred.setClosable(true);
        desktopPane.add(pred);
        pred.show();
}//GEN-LAST:event_requestsButtonActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        ViewDonorRegister donor=null;
        try {
            donor = new ViewDonorRegister();
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }
        donor.setClosable(true);
        desktopPane.add(donor);
        donor.show();
}//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        MobileCampTables mobileCamps = null;
        try {
            try {
                mobileCamps = new MobileCampTables();
            } catch (IOException ex) {
                Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
            }
            mobileCamps.setClosable(true);
            desktopPane.add(mobileCamps);
            mobileCamps.show();
        } catch (SQLException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_jButton26ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        IssueRegister register = null;
        try {
            register = new IssueRegister(desktopPane.getSize());
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }
        register.setClosable(true);
        register.setMaximizable(true);
        desktopPane.add(register);
        desktopPane.setRequestFocusEnabled(true);
        register.show();
        register.setVisible(true);
        register.getSearchPanel().setVisible(false);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        ItemManagement itemStock = null;
        try {
            itemStock = new ItemManagement(null);
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }
        itemStock.setClosable(true);
        desktopPane.add(itemStock);
        itemStock.show();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IssueChart issue = null;
        try {
            issue = new IssueChart(desktopPane.getSize());
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }
        issue.setClosable(true);
        desktopPane.add(issue);
        desktopPane.setRequestFocusEnabled(true);
        issue.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ttiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttiBtnActionPerformed
        AddBloodTypes bloodTypeForm;
        try {
            bloodTypeForm = new AddBloodTypes();
            bloodTypeForm.setClosable(true);
            desktopPane.add(bloodTypeForm);
            desktopPane.setRequestFocusEnabled(true);
            bloodTypeForm.show();
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ttiBtnActionPerformed

    private void bloodGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupBtnActionPerformed
        AddRequestee requestee;
        try {
            requestee = new AddRequestee(null);
            requestee.setClosable(true);
            desktopPane.add(requestee);
            desktopPane.setRequestFocusEnabled(true);
            requestee.show();
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bloodGroupBtnActionPerformed

    private void groupingAndTTIRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupingAndTTIRegButtonActionPerformed

    }//GEN-LAST:event_groupingAndTTIRegButtonActionPerformed

    private void BloodGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodGroupButtonActionPerformed

    }//GEN-LAST:event_BloodGroupButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void testingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testingButtonActionPerformed

    }//GEN-LAST:event_testingButtonActionPerformed

    private void time_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time_txtActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed

    }//GEN-LAST:event_jButton22ActionPerformed

    private void sampleDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleDetailsButtonActionPerformed

    }//GEN-LAST:event_sampleDetailsButtonActionPerformed

    private void issueRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueRegisterButtonActionPerformed

    }//GEN-LAST:event_issueRegisterButtonActionPerformed

    private void generateIssuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateIssuesButtonActionPerformed

    }//GEN-LAST:event_generateIssuesButtonActionPerformed

    private void addSampleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSampleBtnActionPerformed
        AddBloodGroups bloodGroupForm;
        try {
            bloodGroupForm = new AddBloodGroups();
            bloodGroupForm.setClosable(true);
            desktopPane.add(bloodGroupForm);
            desktopPane.setRequestFocusEnabled(true);
            bloodGroupForm.show();
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addSampleBtnActionPerformed

    private void issueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBtnActionPerformed
        AddHospitalWard requestor;
        try {
            requestor = new AddHospitalWard();
            requestor.setClosable(true);
            desktopPane.add(requestor);
            desktopPane.setRequestFocusEnabled(true);
            requestor.show();
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_issueBtnActionPerformed

    private void passwordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordBtnActionPerformed
        ChangePassword passwordReset = null;

        try {
            passwordReset = new ChangePassword(2);
            passwordReset.setClosable(true);
            passwordReset.setMaximizable(false);
            desktopPane.add(passwordReset);
            desktopPane.setRequestFocusEnabled(true);
            passwordReset.show();
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_passwordBtnActionPerformed

    private void groupingAndTTIRegButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupingAndTTIRegButton1ActionPerformed
        GroupingAndTTIRegister register=null;
        try {
            register = new GroupingAndTTIRegister();
        } catch (IOException ex) {
            Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }
        register.setClosable(true);
        register.setMaximizable(true);

        desktopPane.add(register);
        desktopPane.setRequestFocusEnabled(true);
        try {
            register.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        register.show();
    }//GEN-LAST:event_groupingAndTTIRegButton1ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        StockBalance stock = new StockBalance();
        stock.setClosable(true);
        desktopPane.add(stock);
        desktopPane.setRequestFocusEnabled(true);
        stock.show();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void testingButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testingButton1ActionPerformed
        BloodAndComponentAvailability availailityform=null;
        
            try {
                availailityform = new BloodAndComponentAvailability();
            } catch (IOException ex) {
                Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        availailityform.setClosable(true);
        desktopPane.add(availailityform);
        desktopPane.setRequestFocusEnabled(true);
        availailityform.show();
    }//GEN-LAST:event_testingButton1ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Log out", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.dispose();
            Login bbms = new Login();
            bbms.setVisible(true);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        BloodRecievalLog bloodRecieval = new BloodRecievalLog();
        bloodRecieval.setClosable(true);
        desktopPane.add(bloodRecieval);
        desktopPane.setRequestFocusEnabled(true);
        bloodRecieval.show();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void groupingAndTTIRegButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupingAndTTIRegButton2ActionPerformed
        DiscardedBlood discardedBlood = new DiscardedBlood();
        discardedBlood.setClosable(true);
        discardedBlood.setMaximizable(true);
        desktopPane.add(discardedBlood);
        desktopPane.setRequestFocusEnabled(true);
        discardedBlood.show();
    }//GEN-LAST:event_groupingAndTTIRegButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Administrator().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BloodGroupButton;
    private javax.swing.JButton addSampleBtn;
    private javax.swing.JButton bloodGroupBtn;
    private javax.swing.JTextField date_txt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JDesktopPane desktopPane1;
    private javax.swing.JButton generateIssuesButton;
    private javax.swing.JButton groupingAndTTIRegButton;
    private javax.swing.JButton groupingAndTTIRegButton1;
    private javax.swing.JButton groupingAndTTIRegButton2;
    private javax.swing.JButton issueBtn;
    private javax.swing.JButton issueRegisterButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton passwordBtn;
    private javax.swing.JButton requestsButton;
    private javax.swing.JButton sampleDetailsButton;
    private javax.swing.JButton testingButton;
    private javax.swing.JButton testingButton1;
    private javax.swing.JTextField time_txt;
    private javax.swing.JButton ttiBtn;
    // End of variables declaration//GEN-END:variables

}
