/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MedicalOfficer.java
 *
 * Created on Jul 6, 2014, 6:06:59 PM
 */
package view.users;

import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import view.blood_stock_management.AddBloodGroups;
import view.blood_stock_management.AddBloodTypes;
import view.blood_stock_management.StockBalance;
import view.common.ChangePassword;
import view.common.Initial;
import view.common.Login;
import view.issueing.IssueOfBlood;
import view.issueing.IssueRegister;
import view.issueing.SampleDetails;
import view.statistics.Requests;
import view.testing.AddNewTestType;
import view.testing.BloodAndComponentAvailability;
import view.testing.BloodGroupingAndTTI;
import view.testing.DeleteTest;
import view.testing.GroupingAndTTIRegister;

/**
 *
 * @author Anuradha
 */
public class MedicalOfficer extends javax.swing.JFrame {

    /**
     * Creates new form MedicalOfficer
     */
    public MedicalOfficer() throws IOException {
        initComponents();

        File imgfile = new File("..\\BBMS\\src\\images\\drop.png");
        FileInputStream imgStream = new FileInputStream(imgfile);
        BufferedImage bi = ImageIO.read(imgStream);
        ImageIcon myImg = new ImageIcon(bi);
        this.setIconImage(myImg.getImage());
        
        setTitle("Karapitiya Blood Bank Management System");

        Initial first = new Initial(desktopPane.getSize());
        desktopPane.removeAll();
        desktopPane.add(first);
        first.setVisible(true);

        setLocationRelativeTo(null);
        currentDate();
    }

    public JDesktopPane getDesktop() {
        return desktopPane;
    }

    public void currentDate() {

        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    date_txt.setText("Date " + year + "/" + (month + 1) + "/" + day);

                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    time_txt.setText("Time " + hour + ":" + (minute) + ":" + second);

                    try {
                        sleep(1000);
                    } catch (Exception e) {

                    }

                }
            }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ttiBtn = new javax.swing.JButton();
        bloodGroupBtn = new javax.swing.JButton();
        bloodGroupingBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        groupingAndTTIRegButton = new javax.swing.JButton();
        BloodGroupButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        testingButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        sampleDetailsButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        issueRegisterButton = new javax.swing.JButton();
        generateIssuesButton = new javax.swing.JButton();
        addSampleBtn = new javax.swing.JButton();
        issueBtn = new javax.swing.JButton();
        passwordBtn = new javax.swing.JButton();
        issueRegisterBtn1 = new javax.swing.JButton();
        deleteBtn1 = new javax.swing.JButton();
        date_txt = new javax.swing.JTextField();
        time_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blood Bank Management System");

        ttiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TTI test icon.png"))); // NOI18N
        ttiBtn.setToolTipText("TTI Register");
        ttiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttiBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(ttiBtn);
        ttiBtn.setBounds(120, 0, 60, 60);

        bloodGroupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crossmatch.png"))); // NOI18N
        bloodGroupBtn.setToolTipText("Blood Grouping and TTI");
        bloodGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(bloodGroupBtn);
        bloodGroupBtn.setBounds(180, 0, 60, 60);

        bloodGroupingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewRequest.png"))); // NOI18N
        bloodGroupingBtn.setToolTipText("View Requests");
        bloodGroupingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupingBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(bloodGroupingBtn);
        bloodGroupingBtn.setBounds(60, 0, 60, 60);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Karapitiya Blood Bank Management System");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(420, 0, 690, 60);

        desktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        jLayeredPane1.add(desktopPane);
        desktopPane.setBounds(210, 60, 1160, 650);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setFocusTraversalPolicyProvider(true);
        jPanel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        groupingAndTTIRegButton.setBackground(new java.awt.Color(255, 0, 0));
        groupingAndTTIRegButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        groupingAndTTIRegButton.setText("TTI Register");
        groupingAndTTIRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupingAndTTIRegButtonActionPerformed(evt);
            }
        });

        BloodGroupButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        BloodGroupButton.setText("Blood Grouping and TTI");
        BloodGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodGroupButtonActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton5.setText("Delete/Update Test");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton6.setText("Add New Test");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupingAndTTIRegButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BloodGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(groupingAndTTIRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BloodGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel2);
        jPanel2.setBounds(0, 210, 200, 180);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton18.setBackground(new java.awt.Color(255, 0, 0));
        jButton18.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton18.setText("Blood Stock");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton16.setText("Blood Categories");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        testingButton.setBackground(new java.awt.Color(255, 0, 0));
        testingButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        testingButton.setText("Availability");
        testingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(testingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel3);
        jPanel3.setBounds(0, 520, 200, 160);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton22.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        jButton22.setText("View Requests");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        sampleDetailsButton.setBackground(new java.awt.Color(255, 0, 0));
        sampleDetailsButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        sampleDetailsButton.setText("Add Sample Details");
        sampleDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sampleDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sampleDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel4);
        jPanel4.setBounds(0, 90, 200, 110);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Issues", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        issueRegisterButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        issueRegisterButton.setText("Issue Register");
        issueRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueRegisterButtonActionPerformed(evt);
            }
        });

        generateIssuesButton.setBackground(new java.awt.Color(255, 0, 0));
        generateIssuesButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        generateIssuesButton.setText("Generate Issues");
        generateIssuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateIssuesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generateIssuesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
            .addComponent(issueRegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generateIssuesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(issueRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jLayeredPane1.add(jPanel1);
        jPanel1.setBounds(0, 400, 200, 110);

        addSampleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addSample.png"))); // NOI18N
        addSampleBtn.setToolTipText("Add Sample Details");
        addSampleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSampleBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(addSampleBtn);
        addSampleBtn.setBounds(0, 0, 60, 60);

        issueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blood Issue.png"))); // NOI18N
        issueBtn.setToolTipText("Generate Issues");
        issueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(issueBtn);
        issueBtn.setBounds(240, 0, 60, 60);

        passwordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        passwordBtn.setToolTipText("Change Password");
        passwordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(passwordBtn);
        passwordBtn.setBounds(1250, 0, 60, 60);

        issueRegisterBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issueregistericon.png"))); // NOI18N
        issueRegisterBtn1.setToolTipText("Issue Register");
        issueRegisterBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueRegisterBtn1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(issueRegisterBtn1);
        issueRegisterBtn1.setBounds(300, 0, 60, 60);

        deleteBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletetest.png"))); // NOI18N
        deleteBtn1.setToolTipText("Logout");
        deleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(deleteBtn1);
        deleteBtn1.setBounds(1310, 0, 60, 60);

        date_txt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        date_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.add(date_txt);
        date_txt.setBounds(1130, 10, 110, 20);

        time_txt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        time_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        time_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time_txtActionPerformed(evt);
            }
        });
        jLayeredPane1.add(time_txt);
        time_txt.setBounds(1130, 40, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        StockBalance stock = new StockBalance();
        stock.setClosable(true);
        desktopPane.add(stock);
        desktopPane.setRequestFocusEnabled(true);
        stock.show();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void ttiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttiBtnActionPerformed
        GroupingAndTTIRegister register = null;
        try {
            register = new GroupingAndTTIRegister();
        } catch (IOException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        register.setClosable(true);
        register.setMaximizable(true);

        desktopPane.add(register);
        desktopPane.setRequestFocusEnabled(true);
        try {
            register.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        register.show();
}//GEN-LAST:event_ttiBtnActionPerformed

    private void bloodGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupBtnActionPerformed
        BloodGroupingAndTTI groupform = null;

        try {
            groupform = new BloodGroupingAndTTI(desktopPane);
        } catch (IOException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }

        groupform.setClosable(true);
        groupform.setMaximizable(true);
        desktopPane.add(groupform);
        desktopPane.setRequestFocusEnabled(true);
        groupform.show();
}//GEN-LAST:event_bloodGroupBtnActionPerformed

    private void bloodGroupingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupingBtnActionPerformed
        Requests reportC = new Requests(desktopPane);
        reportC.setClosable(true);
        reportC.setMaximizable(true);
        desktopPane.add(reportC);
        desktopPane.setRequestFocusEnabled(true);
        reportC.show();
}//GEN-LAST:event_bloodGroupingBtnActionPerformed

    private void groupingAndTTIRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupingAndTTIRegButtonActionPerformed
        GroupingAndTTIRegister register = null;
        try {
            register = new GroupingAndTTIRegister();
        } catch (IOException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        register.setClosable(true);
        register.setMaximizable(true);

        desktopPane.add(register);
        desktopPane.setRequestFocusEnabled(true);
        try {
            register.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        register.show();
    }//GEN-LAST:event_groupingAndTTIRegButtonActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        Requests reportC = new Requests(desktopPane);
        reportC.setClosable(true);
        reportC.setMaximizable(true);
        desktopPane.add(reportC);
        desktopPane.setRequestFocusEnabled(true);
        reportC.show();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void BloodGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodGroupButtonActionPerformed
        BloodGroupingAndTTI groupform = null;

        try {
            groupform = new BloodGroupingAndTTI(desktopPane);
        } catch (IOException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }

        groupform.setClosable(true);
        groupform.setMaximizable(true);
        desktopPane.add(groupform);
        desktopPane.setRequestFocusEnabled(true);
        groupform.show();

    }//GEN-LAST:event_BloodGroupButtonActionPerformed

    private void testingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testingButtonActionPerformed
        BloodAndComponentAvailability availailityform = null;
        try {
            availailityform = new BloodAndComponentAvailability();
        } catch (IOException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        availailityform.setClosable(true);
        availailityform.setMaximizable(true);
        desktopPane.add(availailityform);
        desktopPane.setRequestFocusEnabled(true);
        availailityform.show();
    }//GEN-LAST:event_testingButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DeleteTest window = new DeleteTest();
        window.setClosable(true);
        window.setMaximizable(true);
        desktopPane.add(window);
        desktopPane.setRequestFocusEnabled(true);
        window.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void sampleDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleDetailsButtonActionPerformed
        SampleDetails sampleDetails = new SampleDetails(desktopPane.getSize());
        sampleDetails.setClosable(true);
        desktopPane.add(sampleDetails);
        desktopPane.setRequestFocusEnabled(true);
        sampleDetails.show();
    }//GEN-LAST:event_sampleDetailsButtonActionPerformed

    private void issueRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueRegisterButtonActionPerformed
        IssueRegister register = null;
        try {
            register = new IssueRegister(desktopPane.getSize());
        } catch (IOException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        register.setClosable(true);
        register.setMaximizable(true);
        desktopPane.add(register);
        desktopPane.setRequestFocusEnabled(true);
        register.show();
        register.setVisible(true);
        register.getSearchPanel().setVisible(false);
    }//GEN-LAST:event_issueRegisterButtonActionPerformed

    private void generateIssuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateIssuesButtonActionPerformed
        IssueOfBlood issue = new IssueOfBlood(desktopPane.getSize());
        issue.setClosable(true);
        issue.setMaximizable(true);
        desktopPane.add(issue);
        desktopPane.setRequestFocusEnabled(true);
        issue.show();
    }//GEN-LAST:event_generateIssuesButtonActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        AddBloodTypes bloodCategories = null;
        try {
            bloodCategories = new AddBloodTypes();
        } catch (IOException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        bloodCategories.setClosable(true);
        desktopPane.add(bloodCategories);
        desktopPane.setRequestFocusEnabled(true);
        bloodCategories.show();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void time_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time_txtActionPerformed

    private void addSampleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSampleBtnActionPerformed
        SampleDetails sampleDetails = new SampleDetails(desktopPane.getSize());
        sampleDetails.setClosable(true);
        desktopPane.add(sampleDetails);
        desktopPane.setRequestFocusEnabled(true);
        sampleDetails.show();
    }//GEN-LAST:event_addSampleBtnActionPerformed

    private void issueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBtnActionPerformed
        IssueOfBlood issue = new IssueOfBlood(desktopPane.getSize());
        issue.setClosable(true);
        issue.setMaximizable(true);
        desktopPane.add(issue);
        desktopPane.setRequestFocusEnabled(true);
        issue.show();
    }//GEN-LAST:event_issueBtnActionPerformed

    private void passwordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordBtnActionPerformed
        ChangePassword passwordReset = null;
        try {
            passwordReset = new ChangePassword(1);
        } catch (IOException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        passwordReset.setClosable(true);
        passwordReset.setMaximizable(false);
        desktopPane.add(passwordReset);
        desktopPane.setRequestFocusEnabled(true);
        passwordReset.show();
    }//GEN-LAST:event_passwordBtnActionPerformed

    private void issueRegisterBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueRegisterBtn1ActionPerformed
        IssueRegister register = null;
        try {
            register = new IssueRegister(desktopPane.getSize());
        } catch (IOException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        register.setClosable(true);
        register.setMaximizable(true);
        desktopPane.add(register);
        desktopPane.setRequestFocusEnabled(true);
        register.show();
        register.setVisible(true);
        register.getSearchPanel().setVisible(false);
    }//GEN-LAST:event_issueRegisterBtn1ActionPerformed

    private void deleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn1ActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Log out", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.dispose();
            Login bbms = new Login();
            bbms.setVisible(true);
        }
    }//GEN-LAST:event_deleteBtn1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AddNewTestType type = null;
        try {
            type = new AddNewTestType(null);
        } catch (IOException ex) {
            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        type.setClosable(true);
        type.setMaximizable(true);
        desktopPane.add(type);
        desktopPane.setRequestFocusEnabled(true);
        type.show();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    
                    try {
                        try {
                            UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
                        } catch (ParseException ex) {
                            Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (UnsupportedLookAndFeelException ex) {
                        Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    new MedicalOfficer().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MedicalOfficer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BloodGroupButton;
    private javax.swing.JButton addSampleBtn;
    private javax.swing.JButton bloodGroupBtn;
    private javax.swing.JButton bloodGroupingBtn;
    private javax.swing.JTextField date_txt;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton generateIssuesButton;
    private javax.swing.JButton groupingAndTTIRegButton;
    private javax.swing.JButton issueBtn;
    private javax.swing.JButton issueRegisterBtn1;
    private javax.swing.JButton issueRegisterButton;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton passwordBtn;
    private javax.swing.JButton sampleDetailsButton;
    private javax.swing.JButton testingButton;
    private javax.swing.JTextField time_txt;
    private javax.swing.JButton ttiBtn;
    // End of variables declaration//GEN-END:variables
}
