/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegistrationOfficer.java
 *
 * Created on Aug 18, 2014, 2:27:46 PM
 */
package view.users;

import Employee.AddEmployee;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import view.common.ChangePassword;
import view.common.Initial;
import view.common.Login;
import view.donor_management.DeleteDonorForm;
import view.donor_management.FormFilledByDonor;
import view.donor_management.UpdateDonorForm;
import view.donor_management.ViewDonorRegister;

/**
 *
 * @author Anuradha
 */
public class RegistrationOfficer extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationOfficer
     */
    public RegistrationOfficer() throws IOException {
        FileInputStream imgStream = null;
        try {
            initComponents();
            File imgfile = new File("..\\BBMS\\src\\images\\drop.png");
            imgStream = new FileInputStream(imgfile);
            BufferedImage bi = ImageIO.read(imgStream);
            ImageIcon myImg = new ImageIcon(bi);
            this.setIconImage(myImg.getImage());
            setTitle("Karapitiya Blood Bank Management System");
            Initial first = new Initial(desktopPane.getSize());
            desktopPane.removeAll();
            desktopPane.add(first);
            first.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                imgStream.close();
            } catch (IOException ex) {
                Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        currentDate();
    }

    public void currentDate() {

        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    date_txt.setText("Date " + year + "/" + (month + 1) + "/" + day);

                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    time_txt.setText("Time " + hour + ":" + (minute) + ":" + second);

                    try {
                        sleep(1000);
                    } catch (Exception e) {

                    }

                }
            }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        desktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        updateDonorBtn = new javax.swing.JButton();
        deleteDonorBtn = new javax.swing.JButton();
        addDonorBtn = new javax.swing.JButton();
        donorRegisterBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        addNewDonorButton = new javax.swing.JButton();
        updateDonorButton = new javax.swing.JButton();
        deleteDonorButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        viewDonorRegisterButton = new javax.swing.JButton();
        passwordBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        date_txt = new javax.swing.JTextField();
        time_txt = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        viewDonorRegisterButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/images/red-blood-cells.png")))); // NOI18N
        jLayeredPane1.add(desktopPane);
        desktopPane.setBounds(200, 60, 1170, 670);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Karapitiya Blood Bank Management System");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(350, 0, 730, 60);

        updateDonorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateButton.png"))); // NOI18N
        updateDonorBtn.setToolTipText("Update Donor");
        updateDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDonorBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(updateDonorBtn);
        updateDonorBtn.setBounds(120, 0, 60, 60);

        deleteDonorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_Icon1.png"))); // NOI18N
        deleteDonorBtn.setToolTipText("Delete Donor");
        deleteDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDonorBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(deleteDonorBtn);
        deleteDonorBtn.setBounds(180, 0, 60, 60);

        addDonorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addSample.png"))); // NOI18N
        addDonorBtn.setToolTipText("Add New Donor");
        addDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonorBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(addDonorBtn);
        addDonorBtn.setBounds(60, 0, 60, 60);

        donorRegisterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issueregistericon.png"))); // NOI18N
        donorRegisterBtn.setToolTipText("Donor Register");
        donorRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorRegisterBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(donorRegisterBtn);
        donorRegisterBtn.setBounds(0, 0, 60, 60);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        addNewDonorButton.setBackground(new java.awt.Color(255, 0, 0));
        addNewDonorButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        addNewDonorButton.setText("Add New Donor");
        addNewDonorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDonorButtonActionPerformed(evt);
            }
        });

        updateDonorButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        updateDonorButton.setText("Update Donor");
        updateDonorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDonorButtonActionPerformed(evt);
            }
        });

        deleteDonorButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteDonorButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        deleteDonorButton.setText("Delete Donor");
        deleteDonorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDonorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteDonorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updateDonorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addNewDonorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewDonorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(updateDonorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(deleteDonorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel8);
        jPanel8.setBounds(0, 190, 200, 170);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        viewDonorRegisterButton.setBackground(new java.awt.Color(255, 0, 0));
        viewDonorRegisterButton.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        viewDonorRegisterButton.setText("Add Employee");
        viewDonorRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDonorRegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewDonorRegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewDonorRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel9);
        jPanel9.setBounds(0, 490, 200, 90);

        passwordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        passwordBtn.setToolTipText("Change Password");
        passwordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(passwordBtn);
        passwordBtn.setBounds(1240, 0, 60, 60);

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletetest.png"))); // NOI18N
        deleteBtn.setToolTipText("Delete/Update Test ");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(deleteBtn);
        deleteBtn.setBounds(1300, 0, 60, 60);

        date_txt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLayeredPane1.add(date_txt);
        date_txt.setBounds(1120, 10, 110, 20);

        time_txt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        time_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time_txtActionPerformed(evt);
            }
        });
        jLayeredPane1.add(time_txt);
        time_txt.setBounds(1120, 40, 110, 20);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Donor Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        viewDonorRegisterButton1.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        viewDonorRegisterButton1.setText("Donor Register");
        viewDonorRegisterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDonorRegisterButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewDonorRegisterButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewDonorRegisterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel10);
        jPanel10.setBounds(0, 380, 200, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewDonorRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDonorRegisterButtonActionPerformed
        // TODO add your handling code here:
        AddEmployee donorRegister = null;
        donorRegister = new AddEmployee();

        donorRegister.setClosable(true);
        donorRegister.setMaximizable(true);
        desktopPane.add(donorRegister);
        desktopPane.setRequestFocusEnabled(true);
        donorRegister.show();
}//GEN-LAST:event_viewDonorRegisterButtonActionPerformed

    private void addNewDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDonorButtonActionPerformed
        FormFilledByDonor donor = null;
        try {
            donor = new FormFilledByDonor();
        } catch (IOException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        donor.setClosable(true);
        donor.setMaximizable(true);
        desktopPane.add(donor);
        desktopPane.setRequestFocusEnabled(true);
        donor.show();
}//GEN-LAST:event_addNewDonorButtonActionPerformed

    private void updateDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDonorButtonActionPerformed
        try {
            UpdateDonorForm update = null;
            try {
                update = new UpdateDonorForm();
            } catch (IOException ex) {
                Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
            }
            update.setClosable(true);
            update.setMaximizable(true);
            desktopPane.add(update);
            desktopPane.setRequestFocusEnabled(true);
            update.show();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateDonorButtonActionPerformed

    private void deleteDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDonorButtonActionPerformed
        DeleteDonorForm deleteDonor = null;
        try {
            deleteDonor = new DeleteDonorForm();
        } catch (IOException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        deleteDonor.setClosable(true);
        deleteDonor.setMaximizable(true);
        desktopPane.add(deleteDonor);
        desktopPane.setRequestFocusEnabled(true);
        deleteDonor.show();
    }//GEN-LAST:event_deleteDonorButtonActionPerformed

    private void updateDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDonorBtnActionPerformed
        try {
            UpdateDonorForm update = null;
            try {
                update = new UpdateDonorForm();
            } catch (IOException ex) {
                Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
            }
            update.setClosable(true);
            update.setMaximizable(true);
            desktopPane.add(update);
            desktopPane.setRequestFocusEnabled(true);
            update.show();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateDonorBtnActionPerformed

    private void deleteDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDonorBtnActionPerformed
        DeleteDonorForm deleteDonor = null;
        try {
            deleteDonor = new DeleteDonorForm();
        } catch (IOException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        deleteDonor.setClosable(true);
        deleteDonor.setMaximizable(true);
        desktopPane.add(deleteDonor);
        desktopPane.setRequestFocusEnabled(true);
        deleteDonor.show();
    }//GEN-LAST:event_deleteDonorBtnActionPerformed

    private void addDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonorBtnActionPerformed
        FormFilledByDonor donor = null;
        try {
            donor = new FormFilledByDonor();
        } catch (IOException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        donor.setClosable(true);
        donor.setMaximizable(true);
        desktopPane.add(donor);
        desktopPane.setRequestFocusEnabled(true);
        donor.show();
    }//GEN-LAST:event_addDonorBtnActionPerformed

    private void donorRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorRegisterBtnActionPerformed
        ViewDonorRegister donorRegister = null;
        try {
            donorRegister = new ViewDonorRegister();
        } catch (IOException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        donorRegister.setClosable(true);
        donorRegister.setMaximizable(true);
        desktopPane.add(donorRegister);
        desktopPane.setRequestFocusEnabled(true);
        donorRegister.show();
    }//GEN-LAST:event_donorRegisterBtnActionPerformed

    private void time_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time_txtActionPerformed

    private void passwordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordBtnActionPerformed
        ChangePassword passwordReset = null;
        try {
            passwordReset = new ChangePassword(4);
        } catch (IOException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        passwordReset.setClosable(true);
        passwordReset.setMaximizable(false);
        desktopPane.add(passwordReset);
        desktopPane.setRequestFocusEnabled(true);
        passwordReset.show();
    }//GEN-LAST:event_passwordBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Log out", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.dispose();
            Login bbms = new Login();
            bbms.setVisible(true);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewDonorRegisterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDonorRegisterButton1ActionPerformed
        ViewDonorRegister donorRegister = null;
        try {
            donorRegister = new ViewDonorRegister();
        } catch (IOException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
        donorRegister.setClosable(true);
        donorRegister.setMaximizable(true);
        desktopPane.add(donorRegister);
        desktopPane.setRequestFocusEnabled(true);
        donorRegister.show();
    }//GEN-LAST:event_viewDonorRegisterButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    try {
                        UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
                    } catch (ParseException ex) {
                        Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    new RegistrationOfficer().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDonorBtn;
    private javax.swing.JButton addNewDonorButton;
    private javax.swing.JTextField date_txt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteDonorBtn;
    private javax.swing.JButton deleteDonorButton;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton donorRegisterBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton passwordBtn;
    private javax.swing.JTextField time_txt;
    private javax.swing.JButton updateDonorBtn;
    private javax.swing.JButton updateDonorButton;
    private javax.swing.JButton viewDonorRegisterButton;
    private javax.swing.JButton viewDonorRegisterButton1;
    // End of variables declaration//GEN-END:variables

}
