/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Aug 20, 2014, 9:42:29 PM
 */
package view.common;

import controller.common.LoginController;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import view.users.Administrator;
import view.users.MedicalOfficer;
import view.users.Nurse;
import view.users.PHI;
import view.users.RegistrationOfficer;

/**
 *
 * @author Anuradha
 */
public class Login extends javax.swing.JFrame {

    LoginController loginController;
    int user;

    /**
     * Creates new form Login2
     */
    public Login() {
        initComponents();
        ImageIcon ii = new javax.swing.ImageIcon(getClass().getResource("/images/drop.png"));
        this.setIconImage(ii.getImage());
        loginController = new LoginController();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        enterPedPanel.setVisible(false);

        //this.setUndecorated(true);
//        File imgfile = new File("..\\BBMS\\src\\images\\drop.png");
//        FileInputStream imgStream = new FileInputStream(imgfile);
//        BufferedImage bi = ImageIO.read(imgStream);
//        ImageIcon myImg = new ImageIcon(bi);
//        this.setIconImage(myImg.getImage());
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        enterPedPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        cancelButton = new javax.swing.JButton();
        switchUserButton = new javax.swing.JButton();
        chosenUserPanel = new javax.swing.JPanel();
        chosenuser = new javax.swing.JLabel();
        allUsersPanel = new javax.swing.JPanel();
        phiButton = new javax.swing.JButton();
        doctorButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        nurseButton = new javax.swing.JButton();
        regOfficerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);

        enterPedPanel.setOpaque(false);
        enterPedPanel.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Password");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyTyped(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        switchUserButton.setText("Switch User");
        switchUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(switchUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, loginButton, switchUserButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(switchUserButton)
                    .addComponent(cancelButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        enterPedPanel.add(jPanel1);
        jPanel1.setBounds(80, 140, 400, 120);

        chosenUserPanel.setLayout(null);

        chosenuser.setFocusable(false);
        chosenuser.setOpaque(true);
        chosenUserPanel.add(chosenuser);
        chosenuser.setBounds(0, 0, 130, 130);

        enterPedPanel.add(chosenUserPanel);
        chosenUserPanel.setBounds(200, 10, 130, 130);

        jLayeredPane1.add(enterPedPanel);
        enterPedPanel.setBounds(0, 90, 550, 270);

        allUsersPanel.setOpaque(false);

        phiButton.setFont(new java.awt.Font("OCR A Extended", 0, 10)); // NOI18N
        phiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PHI.png"))); // NOI18N
        phiButton.setText("PHI");
        phiButton.setToolTipText("PHI");
        phiButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        phiButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        phiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phiButtonActionPerformed(evt);
            }
        });

        doctorButton.setFont(new java.awt.Font("OCR A Extended", 0, 10)); // NOI18N
        doctorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctor.png"))); // NOI18N
        doctorButton.setText("Doctor");
        doctorButton.setToolTipText("Medical Officer");
        doctorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        doctorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        doctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorButtonActionPerformed(evt);
            }
        });

        adminButton.setFont(new java.awt.Font("OCR A Extended", 0, 10)); // NOI18N
        adminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin.png"))); // NOI18N
        adminButton.setText("Admin");
        adminButton.setToolTipText("Administrator");
        adminButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        nurseButton.setFont(new java.awt.Font("OCR A Extended", 0, 10)); // NOI18N
        nurseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nurse_Female_Light.png"))); // NOI18N
        nurseButton.setText("Nurse");
        nurseButton.setToolTipText("Nurse");
        nurseButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nurseButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nurseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseButtonActionPerformed(evt);
            }
        });

        regOfficerButton.setFont(new java.awt.Font("OCR A Extended", 0, 10)); // NOI18N
        regOfficerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RegistrationOfficer.png"))); // NOI18N
        regOfficerButton.setText("Registrar");
        regOfficerButton.setToolTipText("Registration Officer");
        regOfficerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        regOfficerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        regOfficerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regOfficerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout allUsersPanelLayout = new javax.swing.GroupLayout(allUsersPanel);
        allUsersPanel.setLayout(allUsersPanelLayout);
        allUsersPanelLayout.setHorizontalGroup(
            allUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allUsersPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(phiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nurseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regOfficerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        allUsersPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adminButton, doctorButton, nurseButton, phiButton, regOfficerButton});

        allUsersPanelLayout.setVerticalGroup(
            allUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allUsersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(allUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nurseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regOfficerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        allUsersPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adminButton, doctorButton, nurseButton, phiButton, regOfficerButton});

        jLayeredPane1.add(allUsersPanel);
        allUsersPanel.setBounds(0, 100, 550, 117);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel2.setText("National Blood Transfusion Service");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(10, 0, 530, 70);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Blood Bank Management Software - Karapitiya Branch");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(60, 50, 440, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbackground.png"))); // NOI18N
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(0, 0, 550, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phiButtonActionPerformed
        allUsersPanel.setVisible(false);
        enterPedPanel.setVisible(true);
        chosenuser.setOpaque(false);
        user = 0;

        ImageIcon ii = new javax.swing.ImageIcon(getClass().getResource("/images/PHIL.png"));
//        float scale = 1.9f; // 2 times smaller
//        int width = ii.getIconWidth();
//        int height = ii.getIconHeight();
//        int newWidth = Math.round(width * scale);
//        int newheight = Math.round(height * scale);
//        chosenuser.setSize(chosenUserPanel.getWidth(), chosenUserPanel.getHeight());
//        chosenuser.setIcon(new ImageIcon(ii.getImage().getScaledInstance(newWidth, newheight,
//                java.awt.Image.SCALE_SMOOTH)));
        chosenuser.setIcon(ii);
        PasswordField.requestFocus();

}//GEN-LAST:event_phiButtonActionPerformed

    private void doctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorButtonActionPerformed

        allUsersPanel.setVisible(false);
        enterPedPanel.setVisible(true);
        user = 1;

        ImageIcon ii = new javax.swing.ImageIcon(getClass().getResource(
                "/images/doctorL.png"));
//        float scale = 1.9f; // 2 times smaller
//        int width = ii.getIconWidth();
//        int height = ii.getIconHeight();
//        int newWidth = Math.round(width * scale);
//        int newheight = Math.round(height * scale);
//        chosenuser.setSize(chosenUserPanel.getWidth(), chosenUserPanel.getHeight());
//        chosenuser.setIcon(new ImageIcon(ii.getImage().getScaledInstance(newWidth, newheight,
//                java.awt.Image.SCALE_SMOOTH)));
        chosenuser.setIcon(ii);
        PasswordField.requestFocus();
}//GEN-LAST:event_doctorButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        allUsersPanel.setVisible(false);
        enterPedPanel.setVisible(true);
        user = 2;

        ImageIcon ii = new javax.swing.ImageIcon(getClass().getResource(
                "/images/AdminL.png"));
//        float scale = 1.9f; // 2 times smaller
//        int width = ii.getIconWidth();
//        int height = ii.getIconHeight();
//        int newWidth = Math.round(width * scale);
//        int newheight = Math.round(height * scale);
//        chosenuser.setSize(chosenUserPanel.getWidth(), chosenUserPanel.getHeight());
//        chosenuser.setIcon(new ImageIcon(ii.getImage().getScaledInstance(newWidth, newheight,
//                java.awt.Image.SCALE_SMOOTH)));
        chosenuser.setIcon(ii);
        PasswordField.requestFocus();

    }//GEN-LAST:event_adminButtonActionPerformed

    private void nurseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseButtonActionPerformed
        allUsersPanel.setVisible(false);
        enterPedPanel.setVisible(true);

        user = 3;
        ImageIcon ii = new javax.swing.ImageIcon(getClass().getResource("/images/Nurse_Female_LightL.png"));
//        float scale = 1.9f; // 2 times smaller
//        int width = ii.getIconWidth();
//        int height = ii.getIconHeight();
//        int newWidth = Math.round(width * scale);
//        int newheight = Math.round(height * scale);
//        chosenuser.setSize(chosenUserPanel.getWidth(), chosenUserPanel.getHeight());
//        chosenuser.setIcon(new ImageIcon(ii.getImage().getScaledInstance(newWidth, newheight,
//                java.awt.Image.SCALE_SMOOTH)));
        chosenuser.setIcon(ii);
        PasswordField.requestFocus();
}//GEN-LAST:event_nurseButtonActionPerformed

    private void regOfficerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regOfficerButtonActionPerformed
        allUsersPanel.setVisible(false);
        enterPedPanel.setVisible(true);
        user = 4;
        ImageIcon ii = new javax.swing.ImageIcon(getClass().getResource("/images/RegistrationOfficerL.png"));
//        float scale = 1.9f; // 2 times smaller
//        int width = ii.getIconWidth();
//        int height = ii.getIconHeight();
//        int newWidth = Math.round(width * scale);
//        int newheight = Math.round(height * scale);
//        chosenuser.setSize(chosenUserPanel.getWidth(), chosenUserPanel.getHeight());
//        chosenuser.setIcon(new ImageIcon(ii.getImage().getScaledInstance(newWidth, newheight,
//                java.awt.Image.SCALE_SMOOTH)));
        chosenuser.setIcon(ii);
        PasswordField.requestFocus();
}//GEN-LAST:event_regOfficerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        allUsersPanel.setVisible(false);
        enterPedPanel.setVisible(true);
        boolean isValid = false;
        try {
            isValid = loginController.isValidPassword(user, PasswordField.getPassword());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if (isValid) {
                if (user == 2) {
                    Administrator admin;
                    admin = new Administrator();
                    this.dispose();
                    admin.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    admin.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                    admin.setVisible(true);
                    //admin.setState(JFrame.ICONIFIED);
                    //admin.setState(JFrame.NORMAL);
                } else if (user == 1) {
                    MedicalOfficer mo;
                    mo = new MedicalOfficer();
                    this.dispose();
                    //mo.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    mo.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                    mo.setVisible(true);
                } else if (user == 3) {
                    Nurse nurse;
                    nurse = new Nurse();
                    this.dispose();
                    //nurse.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    nurse.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                    nurse.setVisible(true);
                } else if (user == 0) {
                    PHI phi;
                    phi = new PHI();
                    this.dispose();
                    //phi.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    phi.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                    phi.setVisible(true);
                } else if (user == 4) {
                    RegistrationOfficer ro;
                    ro = new RegistrationOfficer();
                    this.dispose();
                    //ro.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    ro.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                    ro.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect password. Please try again!", "Error", JOptionPane.ERROR_MESSAGE);
                PasswordField.setText(null);
            }
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_loginButtonActionPerformed

    private void switchUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchUserButtonActionPerformed
        enterPedPanel.setVisible(false);
        allUsersPanel.setVisible(true);
        PasswordField.setText(null);
    }//GEN-LAST:event_switchUserButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void PasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyTyped
        char c = evt.getKeyChar();

        if (c == java.awt.event.KeyEvent.VK_ENTER) {
            allUsersPanel.setVisible(false);
            enterPedPanel.setVisible(true);
            boolean isValid = false;
            try {
                isValid = loginController.isValidPassword(user, PasswordField.getPassword());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if (isValid) {
                    if (user == 2) {
                        Administrator admin;
                        admin = new Administrator();
                        this.dispose();
                        admin.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        admin.setVisible(true);
                    } else if (user == 1) {
                        MedicalOfficer mo;
                        mo = new MedicalOfficer();
                        this.dispose();
                        mo.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        mo.setVisible(true);
                    } else if (user == 3) {
                        Nurse nurse;
                        nurse = new Nurse();
                        this.dispose();
                        nurse.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        nurse.setVisible(true);
                    } else if (user == 0) {
                        PHI phi;
                        phi = new PHI();
                        this.dispose();
                        phi.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        phi.setVisible(true);
                    } else if (user == 4) {
                        RegistrationOfficer ro;
                        ro = new RegistrationOfficer();
                        this.dispose();
                        ro.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        ro.setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect password. Please try again!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_PasswordFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton adminButton;
    private javax.swing.JPanel allUsersPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel chosenUserPanel;
    private javax.swing.JLabel chosenuser;
    private javax.swing.JButton doctorButton;
    private javax.swing.JPanel enterPedPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton nurseButton;
    private javax.swing.JButton phiButton;
    private javax.swing.JButton regOfficerButton;
    private javax.swing.JButton switchUserButton;
    // End of variables declaration//GEN-END:variables

}
