/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegistrationOfficer.java
 *
 * Created on Aug 18, 2014, 2:27:46 PM
 */
package gui.Upekka;

import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import gui.Naduni.Initial;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Anuradha
 */
public class RegistrationOfficer extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationOfficer
     */
    public RegistrationOfficer() throws IOException {
        FileInputStream imgStream = null;
        try {
            initComponents();
            File imgfile = new File("..\\BBMS\\src\\images\\drop.png");
            imgStream = new FileInputStream(imgfile);
            BufferedImage bi = ImageIO.read(imgStream);
            ImageIcon myImg = new ImageIcon(bi);
            this.setIconImage(myImg.getImage());
            
            Initial first = new Initial(desktopPane.getSize());
        desktopPane.removeAll();
        desktopPane.add(first);
        first.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                imgStream.close();
            } catch (IOException ex) {
                Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        currentDate();
    }
    
    public void currentDate() {

        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    date_txt.setText("Date " + year + "/" + (month + 1) + "/" + day);

                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    time_txt.setText("Time " + hour + ":" + (minute) + ":" + second);

                    try {
                        sleep(1000);
                    } catch (Exception e) {

                    }

                }
            }
        };
        clock.start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        desktopPane = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        viewDonorRegisterButton = new javax.swing.JButton();
        addNewDonorButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        deleteDonorButton = new javax.swing.JButton();
        updateDonorButton = new javax.swing.JButton();
        updateDonorBtn = new javax.swing.JButton();
        deleteDonorBtn = new javax.swing.JButton();
        addDonorBtn = new javax.swing.JButton();
        donorRegisterBtn = new javax.swing.JButton();
        date_txt = new javax.swing.JTextField();
        time_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/images/red-blood-cells.png")))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registration Officer");
        desktopPane.add(jLabel3);
        jLabel3.setBounds(370, 0, 310, 50);

        jLayeredPane1.add(desktopPane);
        desktopPane.setBounds(200, 60, 1150, 650);

        viewDonorRegisterButton.setBackground(new java.awt.Color(255, 51, 51));
        viewDonorRegisterButton.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        viewDonorRegisterButton.setText("Donor Register");
        viewDonorRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDonorRegisterButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(viewDonorRegisterButton);
        viewDonorRegisterButton.setBounds(0, 160, 200, 30);

        addNewDonorButton.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        addNewDonorButton.setText("Add New Donor");
        addNewDonorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDonorButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(addNewDonorButton);
        addNewDonorButton.setBounds(0, 200, 200, 30);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Vijaya", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Karapitiya Blood Bank Management System");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(420, 0, 660, 50);

        deleteDonorButton.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        deleteDonorButton.setText("Delete Donor");
        deleteDonorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDonorButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(deleteDonorButton);
        deleteDonorButton.setBounds(0, 280, 200, 30);

        updateDonorButton.setBackground(new java.awt.Color(255, 51, 51));
        updateDonorButton.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        updateDonorButton.setText("Update Donor");
        updateDonorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDonorButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(updateDonorButton);
        updateDonorButton.setBounds(0, 240, 200, 30);

        updateDonorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateButton.png"))); // NOI18N
        updateDonorBtn.setToolTipText("Update Donor");
        updateDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDonorBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(updateDonorBtn);
        updateDonorBtn.setBounds(120, 0, 60, 60);

        deleteDonorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_Icon1.png"))); // NOI18N
        deleteDonorBtn.setToolTipText("Delete Donor");
        deleteDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDonorBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(deleteDonorBtn);
        deleteDonorBtn.setBounds(180, 0, 60, 60);

        addDonorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addSample.png"))); // NOI18N
        addDonorBtn.setToolTipText("Add New Donor");
        addDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonorBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(addDonorBtn);
        addDonorBtn.setBounds(60, 0, 60, 60);

        donorRegisterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issueregistericon.png"))); // NOI18N
        donorRegisterBtn.setToolTipText("Donor Register");
        donorRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorRegisterBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(donorRegisterBtn);
        donorRegisterBtn.setBounds(0, 0, 60, 60);

        date_txt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLayeredPane1.add(date_txt);
        date_txt.setBounds(1230, 0, 110, 20);

        time_txt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        time_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time_txtActionPerformed(evt);
            }
        });
        jLayeredPane1.add(time_txt);
        time_txt.setBounds(1230, 30, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewDonorRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDonorRegisterButtonActionPerformed
        // TODO add your handling code here:
        ViewDonorRegister donorRegister = new ViewDonorRegister();
        donorRegister.setClosable(true);
        donorRegister.setMaximizable(true);
        desktopPane.add(donorRegister);
        desktopPane.setRequestFocusEnabled(true);
        donorRegister.show();
}//GEN-LAST:event_viewDonorRegisterButtonActionPerformed

    private void addNewDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDonorButtonActionPerformed
        FormFilledByDonor donor = new FormFilledByDonor();
        donor.setClosable(true);
        donor.setMaximizable(true);
        desktopPane.add(donor);
        desktopPane.setRequestFocusEnabled(true);
        donor.show();
}//GEN-LAST:event_addNewDonorButtonActionPerformed

    private void updateDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDonorButtonActionPerformed
        try {
            UpdateDonorForm update = new UpdateDonorForm();
            update.setClosable(true);
            update.setMaximizable(true);
            desktopPane.add(update);
            desktopPane.setRequestFocusEnabled(true);
            update.show();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateDonorButtonActionPerformed

    private void deleteDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDonorButtonActionPerformed
        DeleteDonorForm deleteDonor = new DeleteDonorForm();
        deleteDonor.setClosable(true);
        deleteDonor.setMaximizable(true);
        desktopPane.add(deleteDonor);
        desktopPane.setRequestFocusEnabled(true);
        deleteDonor.show();
    }//GEN-LAST:event_deleteDonorButtonActionPerformed

    private void updateDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDonorBtnActionPerformed
        try {
            UpdateDonorForm update = new UpdateDonorForm();
            update.setClosable(true);
            update.setMaximizable(true);
            desktopPane.add(update);
            desktopPane.setRequestFocusEnabled(true);
            update.show();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateDonorBtnActionPerformed

    private void deleteDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDonorBtnActionPerformed
        DeleteDonorForm deleteDonor = new DeleteDonorForm();
        deleteDonor.setClosable(true);
        deleteDonor.setMaximizable(true);
        desktopPane.add(deleteDonor);
        desktopPane.setRequestFocusEnabled(true);
        deleteDonor.show();
    }//GEN-LAST:event_deleteDonorBtnActionPerformed

    private void addDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonorBtnActionPerformed
        FormFilledByDonor donor = new FormFilledByDonor();
        donor.setClosable(true);
        donor.setMaximizable(true);
        desktopPane.add(donor);
        desktopPane.setRequestFocusEnabled(true);
        donor.show();
    }//GEN-LAST:event_addDonorBtnActionPerformed

    private void donorRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorRegisterBtnActionPerformed
        ViewDonorRegister donorRegister = new ViewDonorRegister();
        donorRegister.setClosable(true);
        donorRegister.setMaximizable(true);
        desktopPane.add(donorRegister);
        desktopPane.setRequestFocusEnabled(true);
        donorRegister.show();
    }//GEN-LAST:event_donorRegisterBtnActionPerformed

    private void time_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    try {
                        UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
                    } catch (ParseException ex) {
                        Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    new RegistrationOfficer().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(RegistrationOfficer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDonorBtn;
    private javax.swing.JButton addNewDonorButton;
    private javax.swing.JTextField date_txt;
    private javax.swing.JButton deleteDonorBtn;
    private javax.swing.JButton deleteDonorButton;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton donorRegisterBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField time_txt;
    private javax.swing.JButton updateDonorBtn;
    private javax.swing.JButton updateDonorButton;
    private javax.swing.JButton viewDonorRegisterButton;
    // End of variables declaration//GEN-END:variables

}
