/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddHospitalWard.java
 *
 * Created on Sep 7, 2014, 10:13:03 PM
 */
package view.issueing;

import controller.issueing.HospitalController;
import controller.issueing.WardController;
import controller.common.SearchableCombo;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Requester;
import model.Ward;

/**
 *
 * @author Anuradha
 */
public class AddHospitalWard extends javax.swing.JInternalFrame {

    private String oldHospitalName = "";
    private String oldWardName = "";

    /**
     * Creates new form AddRequestor
     */
    public AddHospitalWard() throws FileNotFoundException, IOException {
        initComponents();
        
        FileInputStream imgStream = null;
        File imgfile = new File("..\\BBMS\\src\\images\\drop.png");
        imgStream = new FileInputStream(imgfile);
        BufferedImage bi = ImageIO.read(imgStream);
        ImageIcon myImg = new ImageIcon(bi);
        this.setFrameIcon(myImg);
        setTitle("Hospitals/Wards");
        this.setBounds(0, 0, 360, 430);
        
        setComboData();
        setWardComboData();
    }

    private void setComboData() {
        try {
            hospitalCombo.removeAllItems();
            ResultSet rst = HospitalController.getAllHospitals();
            while (rst.next()) {
                String hospital = rst.getString("Name");
                hospitalCombo.addItem(hospital);
            }
            new SearchableCombo().setSearchableCombo(hospitalCombo, true);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setWardComboData() {
        try {
            wardCombo.removeAllItems();
            ResultSet rst = WardController.getAllWards();
            while (rst.next()) {
                String ward = rst.getString("Name");
                wardCombo.addItem(ward);
            }
            new SearchableCombo().setSearchableCombo(wardCombo, true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addHospitalText = new javax.swing.JTextField();
        addHospitalBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        addWardText = new javax.swing.JTextField();
        addWardBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        hospitalCombo = new javax.swing.JComboBox();
        updateHospitalText = new javax.swing.JTextField();
        deleteHospitalBtn = new javax.swing.JButton();
        updateHospitalBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        wardCombo = new javax.swing.JComboBox();
        UpdateWardText = new javax.swing.JTextField();
        deleteWardBtn = new javax.swing.JButton();
        updateWardBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(644, 436));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Hospitals/Wards");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 30, 220, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SmallFormHeader.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 11, 607, 73);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hospitals/Wards"));

        jLabel1.setText("Hospital*");

        addHospitalText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addHospitalTextKeyTyped(evt);
            }
        });

        addHospitalBtn.setText("Add");
        addHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHospitalBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Ward*");

        addWardText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addWardTextKeyTyped(evt);
            }
        });

        addWardBtn.setText("Add");
        addWardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWardBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Select Hospital");

        hospitalCombo.setEditable(true);
        hospitalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalComboActionPerformed(evt);
            }
        });

        updateHospitalText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateHospitalTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateHospitalTextKeyTyped(evt);
            }
        });

        deleteHospitalBtn.setText("Delete Hospital");
        deleteHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHospitalBtnActionPerformed(evt);
            }
        });

        updateHospitalBtn.setText("Update Hospital");
        updateHospitalBtn.setEnabled(false);
        updateHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateHospitalBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Select Ward");

        wardCombo.setEditable(true);
        wardCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardComboActionPerformed(evt);
            }
        });

        UpdateWardText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpdateWardTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UpdateWardTextKeyTyped(evt);
            }
        });

        deleteWardBtn.setText("Delete Ward");
        deleteWardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteWardBtnActionPerformed(evt);
            }
        });

        updateWardBtn.setText("Update Ward");
        updateWardBtn.setEnabled(false);
        updateWardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addWardBtn)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addHospitalBtn)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(addHospitalText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(addWardText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(deleteHospitalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateHospitalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateHospitalText)
                                    .addComponent(hospitalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UpdateWardText)
                                    .addComponent(wardCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteWardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateWardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(addHospitalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addHospitalBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hospitalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateHospitalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateHospitalBtn)
                            .addComponent(deleteHospitalBtn))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(wardCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateWardText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(addWardText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addWardBtn)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateWardBtn)
                    .addComponent(deleteWardBtn))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 95, 602, 293);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addHospitalTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addHospitalTextKeyTyped
        if (addHospitalText.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_addHospitalTextKeyTyped

    private void addHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHospitalBtnActionPerformed
        try {
            if (addHospitalText.getText().length() < 1) {
                JOptionPane.showMessageDialog(null, "Error: Please fill the required fields!");
            } else {
                String hospital = addHospitalText.getText();
                Requester requestor = new Requester(hospital);
                int res = HospitalController.addRequestor(requestor);

                if (res == 1) {
                    JOptionPane.showMessageDialog(null, "Added Succesfully");
                    addHospitalText.setText("");
                    setComboData();

                } else {
                    JOptionPane.showMessageDialog(null, "Error!");
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addHospitalBtnActionPerformed

    private void addWardTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addWardTextKeyTyped
        if (addWardText.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_addWardTextKeyTyped

    private void addWardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWardBtnActionPerformed
        try {
            if (addWardText.getText().length() < 1) {
                JOptionPane.showMessageDialog(null, "Error: Please fill the required fields!");
            } else {
                String newWard = addWardText.getText();
                Ward ward = new Ward(newWard);
                int res = WardController.addWard(ward);

                if (res == 1) {
                    JOptionPane.showMessageDialog(null, "Added Succesfully");
                    addWardText.setText("");
                    setWardComboData();

                } else {
                    JOptionPane.showMessageDialog(null, "Error!");
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addWardBtnActionPerformed

    private void hospitalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalComboActionPerformed
        oldHospitalName = "" + hospitalCombo.getSelectedItem();
        updateHospitalText.setText(oldHospitalName);
        updateHospitalBtn.setEnabled(false);
        deleteHospitalBtn.setEnabled(true);
    }//GEN-LAST:event_hospitalComboActionPerformed

    private void updateHospitalTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateHospitalTextKeyPressed

    }//GEN-LAST:event_updateHospitalTextKeyPressed

    private void updateHospitalTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateHospitalTextKeyTyped
        updateHospitalBtn.setEnabled(true);
        deleteHospitalBtn.setEnabled(false);
        if (updateHospitalText.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_updateHospitalTextKeyTyped

    private void deleteHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteHospitalBtnActionPerformed
        try {
            Requester deletedHospital = new Requester(updateHospitalText.getText());
            int res = HospitalController.deleteHospital(deletedHospital);
            if (res == 1) {
                JOptionPane.showMessageDialog(null, "Deleted Succesfully");
                setComboData();

            } else {
                JOptionPane.showMessageDialog(null, "Error!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: To delete this hospital you need to delete all the other records having this hospital!");
        }
    }//GEN-LAST:event_deleteHospitalBtnActionPerformed

    private void updateHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateHospitalBtnActionPerformed
        try {
            if (updateHospitalText.getText().length() < 1) {
                JOptionPane.showMessageDialog(null, "Error: Please fill the required fields!");
            } else {
                Requester oldHospital = new Requester(oldHospitalName);
                Requester newHospital = new Requester(updateHospitalText.getText());
                int res = HospitalController.updateHospital(oldHospital, newHospital);
                if (res == 1) {
                    JOptionPane.showMessageDialog(null, "Updated Succesfully");
                    updateHospitalText.setText("");
                    setComboData();
                    updateHospitalBtn.setEnabled(false);

                } else {
                    JOptionPane.showMessageDialog(null, "Error!");
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: To update this hospital you need to delete all the other records having this hospital!");
        }
    }//GEN-LAST:event_updateHospitalBtnActionPerformed

    private void wardComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardComboActionPerformed
        oldWardName = "" + wardCombo.getSelectedItem();
        UpdateWardText.setText(oldWardName);
        updateWardBtn.setEnabled(false);
        deleteWardBtn.setEnabled(true);
    }//GEN-LAST:event_wardComboActionPerformed

    private void UpdateWardTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpdateWardTextKeyPressed

    }//GEN-LAST:event_UpdateWardTextKeyPressed

    private void UpdateWardTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpdateWardTextKeyTyped
        updateWardBtn.setEnabled(true);
        deleteWardBtn.setEnabled(false);
        if (UpdateWardText.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_UpdateWardTextKeyTyped

    private void deleteWardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteWardBtnActionPerformed
        try {
            Ward deletedWard = new Ward(UpdateWardText.getText());
            int res = WardController.deleteWard(deletedWard);
            if (res == 1) {
                JOptionPane.showMessageDialog(null, "Deleted Succesfully");
                setWardComboData();

            } else {
                JOptionPane.showMessageDialog(null, "Error!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: To delete this ward you need to delete all the other records having this ward!");
        }
    }//GEN-LAST:event_deleteWardBtnActionPerformed

    private void updateWardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateWardBtnActionPerformed
        try {
            if (UpdateWardText.getText().length() < 1) {
                JOptionPane.showMessageDialog(null, "Error: Please fill the required fields!");
            } else {
                Ward oldWard = new Ward(oldWardName);
                Ward newWard = new Ward(UpdateWardText.getText());
                int res = WardController.updateWard(oldWard, newWard);
                if (res == 1) {
                    JOptionPane.showMessageDialog(null, "Updated Succesfully");
                    UpdateWardText.setText("");
                    setWardComboData();
                    updateWardBtn.setEnabled(false);

                } else {
                    JOptionPane.showMessageDialog(null, "Error!");
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddHospitalWard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: To update this ward you need to delete all the other records having this ward!");
        }
    }//GEN-LAST:event_updateWardBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UpdateWardText;
    private javax.swing.JButton addHospitalBtn;
    private javax.swing.JTextField addHospitalText;
    private javax.swing.JButton addWardBtn;
    private javax.swing.JTextField addWardText;
    private javax.swing.JButton deleteHospitalBtn;
    private javax.swing.JButton deleteWardBtn;
    private javax.swing.JComboBox hospitalCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton updateHospitalBtn;
    private javax.swing.JTextField updateHospitalText;
    private javax.swing.JButton updateWardBtn;
    private javax.swing.JComboBox wardCombo;
    // End of variables declaration//GEN-END:variables
}
