/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.Ruchi;

import Controller.Ruchi.TestController;
import Controller.Ruchi.TestResultController;
import controller.TableResizer;
import gui.Anu.ReagentRequests;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ruchiranga
 */
public class GroupingAndTTIRegister extends javax.swing.JInternalFrame {

    DefaultTableModel dtm;
    TestController testController;
    TestResultController testResultController;

    /**
     * Creates new form GroupingAndTTIRegister
     */
    public GroupingAndTTIRegister() {
        initComponents();
        dtm = new DefaultTableModel();
        testController = new TestController();
        testResultController = new TestResultController();
        String name = "";

        String[] tests = null;
        try {
            tests = testController.getTestList();
        } catch (SQLException ex) {
            Logger.getLogger(GroupingAndTTIRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GroupingAndTTIRegister.class.getName()).log(Level.SEVERE, null, ex);
        }

        String[] columns = new String[tests.length + 6];
        columns[0] = "Date";
        columns[1] = "PacketID";
        System.arraycopy(tests, 0, columns, 2, tests.length);
        columns[tests.length + 2] = "Group";
        columns[tests.length + 3] = "Checked By";
        columns[tests.length + 4] = "Done By";
        columns[tests.length + 5] = "Labeled By";
        //String[] columns = {"Date", "Packet ID", "Blood Group", "Checked BY", "DoneBy", "Labeled By"};
        dtm = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        registerTable.setModel(dtm);
        String[][] testResultRecords = null;

        try {
            testResultRecords = testResultController.getTestResultRecords(columns.length);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GroupingAndTTIRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GroupingAndTTIRegister.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (String[] row : testResultRecords) {
            dtm.addRow(row);
        }
        //registerTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableResizer.resizeColumnWidth(registerTable);

        registerTable.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        registerTable = new javax.swing.JTable();
        printButton = new javax.swing.JButton();

        setTitle("Grouping And TTI Register");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        registerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(registerTable);

        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Print.png"))); // NOI18N
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1138, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printButton)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            JasperReport jr = JasperCompileManager.compileReport("./src/Reports/Ruchi/GroupingAndTTIRegisterReport.jrxml");
            Map<String, Object> params;
            params = new HashMap<String, Object>();

            JRTableModelDataSource dataSource = new JRTableModelDataSource(registerTable.getModel());

            JasperPrint jp = JasperFillManager.fillReport(jr, params, dataSource);

            JasperViewer.viewReport(jp,false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, "Error while generating the Report!", "", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ReagentRequests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton printButton;
    private javax.swing.JTable registerTable;
    // End of variables declaration//GEN-END:variables
}
