/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.Naduni;

import controller.SampleDetailsController;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Hospital;
import model.SampleDetail;
import gui.Anu.AddHospitalWard;

/**
 *
 * @author Nands
 */
public class SampleDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form SampleDetails
     */
    public SampleDetails(Dimension d) {
        initComponents();
        setSize(d);
        setHospitalCombo(hospitalCombo);
        setWardCombo(wardCombo);
        symptomLabel.setEnabled(false);
        symptomText.setEnabled(false);

    }

    public JLabel getSymptomLabel() {
        return this.symptomLabel;
    }

    public JTextField getSymptomText() {
        return this.symptomText;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        requestIDText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CollectorText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bhtText = new javax.swing.JTextField();
        maleRadio = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        groupCombo = new javax.swing.JComboBox();
        reactionYesRadio = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        reactionNoRadio = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        femaleRadio = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        ageText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        conditionText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        symptomText = new javax.swing.JTextField();
        hospitalCombo = new javax.swing.JComboBox();
        symptomLabel = new javax.swing.JLabel();
        weightText = new javax.swing.JTextField();
        wardCombo = new javax.swing.JComboBox();
        addTime = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jLabel19 = new javax.swing.JLabel();
        recievedDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        priorityCombo = new javax.swing.JComboBox();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SampleInterface.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Stencil Std", 3, 18)); // NOI18N
        jLabel12.setText("Request ID*");

        requestIDText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        requestIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestIDTextActionPerformed(evt);
            }
        });
        requestIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                requestIDTextKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Collected By:");

        CollectorText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CollectorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollectorTextActionPerformed(evt);
            }
        });
        CollectorText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CollectorTextKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setText("Collected Date*");

        dateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateChooserKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel18.setText("Collected Time*");

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 2, true));

        bhtText.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        bhtText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhtTextActionPerformed(evt);
            }
        });
        bhtText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bhtTextKeyTyped(evt);
            }
        });

        buttonGroup7.add(maleRadio);
        maleRadio.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        maleRadio.setText("Male");
        maleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel16.setText("Ward*");

        groupCombo.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        groupCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        groupCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupComboActionPerformed(evt);
            }
        });

        buttonGroup1.add(reactionYesRadio);
        reactionYesRadio.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        reactionYesRadio.setText("Yes");
        reactionYesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reactionYesRadioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel10.setText("Sex*");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("BHT No*");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("Patients's Group(ABO/Rh D)*");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel8.setText("Hospital*");

        buttonGroup1.add(reactionNoRadio);
        reactionNoRadio.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        reactionNoRadio.setText("No");
        reactionNoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reactionNoRadioActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel15.setText("Age*");

        buttonGroup7.add(femaleRadio);
        femaleRadio.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        femaleRadio.setText("Female");
        femaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setText("H/O of any Transfusion reactions");

        nameText.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextKeyTyped(evt);
            }
        });

        ageText.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        ageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextActionPerformed(evt);
            }
        });
        ageText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageTextKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setText("Weight(kg)");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("Diagnosis/Clinical condition");

        conditionText.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        conditionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                conditionTextKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Name*");

        symptomText.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        symptomText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symptomTextActionPerformed(evt);
            }
        });
        symptomText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                symptomTextKeyTyped(evt);
            }
        });

        hospitalCombo.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        hospitalCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unknown" }));
        hospitalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalComboActionPerformed(evt);
            }
        });

        symptomLabel.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        symptomLabel.setText("Symptoms/Signs");

        weightText.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        weightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTextActionPerformed(evt);
            }
        });
        weightText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weightTextKeyTyped(evt);
            }
        });

        wardCombo.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        wardCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unknown" }));
        wardCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(hospitalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(41, 41, 41))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(28, 28, 28)))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(maleRadio)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(femaleRadio)))
                                    .addGap(18, 18, 18)))
                            .addComponent(bhtText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(138, 138, 138))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel16))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(weightText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(wardCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(1, 1, 1))))
                        .addComponent(symptomLabel)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conditionText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(groupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(reactionYesRadio)
                                .addGap(18, 18, 18)
                                .addComponent(reactionNoRadio))
                            .addComponent(symptomText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(maleRadio)
                                    .addComponent(femaleRadio)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(weightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(bhtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(hospitalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wardCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(groupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(conditionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(reactionYesRadio)
                    .addComponent(reactionNoRadio))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(symptomLabel)
                    .addComponent(symptomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel19.setText("Recieved Date*");

        recievedDateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recievedDateChooserKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CollectorText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recievedDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(addTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(requestIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(requestIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CollectorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(recievedDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addComponent(addTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cute-Ball.png"))); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder-flower-green-icon.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Priority");

        priorityCombo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        priorityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Urgent", "Routine" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priorityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(32, 32, 32)
                .addComponent(add)
                .addGap(186, 186, 186))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(priorityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setHospitalCombo(JComboBox combo) {
        try {
            combo.removeAllItems();
            ResultSet rst = null;
            rst = SampleDetailsController.getAllHospitals();

            while (rst.next()) {
                combo.addItem(rst.getString("Name"));
            }

        } catch (SQLException ex) {
            //Logger.getLogger(BloodPacketForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SampleDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setWardCombo(JComboBox combo) {
        try {
            combo.removeAllItems();
            ResultSet rst = null;
            rst = SampleDetailsController.getAllWards();

            while (rst.next()) {
                combo.addItem(rst.getString("Name"));
            }

        } catch (SQLException ex) {
            //Logger.getLogger(BloodPacketForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SampleDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        try {
            String empty = "";
            String requestID = requestIDText.getText();
            String name = nameText.getText();
            String bloodGroup = "" + groupCombo.getSelectedItem();
            int age = Integer.parseInt(ageText.getText());

            String gender = "";
            if (maleRadio.isSelected()) {
                gender = "Male";
            } else {
                gender = "Female";
            }

            String weight = weightText.getText();
            String hospital = "" + hospitalCombo.getSelectedItem();
            String bht = bhtText.getText();
            String ward = "" + wardCombo.getSelectedItem();
            String condition = "" + conditionText.getText();

            String symptoms = "";
            if (reactionYesRadio.isSelected()) {
                symptoms = symptomText.getText();
            }

            String collector = CollectorText.getText();

            /*Collection date*/
            java.util.Date collectedDate = dateChooser.getDate();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String dateCollection = df.format(collectedDate);
            java.sql.Date sqlDateC = new java.sql.Date(collectedDate.getTime());

            /*collectonTime*/
            SimpleDateFormat formatter = new SimpleDateFormat("hh:mm:ss");
            java.sql.Time sqlTime = null;
            try {
                sqlTime = new java.sql.Time(formatter.parse(addTime.getFormatedTime()).getTime());
            } catch (ParseException ex) {
                Logger.getLogger(SampleDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

            String priority = "" + priorityCombo.getSelectedItem();

            /*Recieved date*/
            java.util.Date receivededDate = recievedDateChooser.getDate();
            df = new SimpleDateFormat("yyyy-MM-dd");
            String dateOfRecieval = df.format(receivededDate);
            java.sql.Date sqlDateR = new java.sql.Date(receivededDate.getTime());

            if (name.equals(empty) || requestID.equals(empty) || bloodGroup.equals(empty) || gender.equals(empty) || dateCollection.equals(empty) || bht.equals(empty) || ward.equals(empty) || hospital.equals(empty) || sqlTime.equals(empty) || sqlDateR.equals(empty)) {
                JOptionPane.showMessageDialog(null, "Please fill the required fields", "Warning!", JOptionPane.WARNING_MESSAGE);
            } else {
                int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to add the sample ?", "Add Sample", JOptionPane.YES_NO_OPTION);
                if (confirm == 0) {
                    try {

                        SampleDetail sample = new SampleDetail(requestID, name, bht, age, gender, bloodGroup, ward, weight, hospital, condition, symptoms, sqlDateC, sqlTime, collector, priority, sqlDateR);

                        int added = 0;
                        try {
                            added = SampleDetailsController.addSample(sample);
                        } catch (SQLException ex) {
                            Logger.getLogger(SampleDetails.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if (added == 1) {
                            JOptionPane.showMessageDialog(null, "Added Succesfully !", "Add Sample", JOptionPane.INFORMATION_MESSAGE);
                            int p = JOptionPane.showConfirmDialog(null, "Do you want to add more samples?", "Continue", JOptionPane.YES_NO_OPTION);

                            if (p == 0) {
                                clear();
                            } else {
                                this.setVisible(false);
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Error!");
                        }
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(SampleDetails.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please fill the required fields", "Warning!", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_addActionPerformed

    private void clear() {
        requestIDText.setText("");
        ageText.setText("");
        nameText.setText("");
        maleRadio.setSelected(false);
        femaleRadio.setSelected(false);
        weightText.setText("");
        hospitalCombo.setEnabled(true);
        bhtText.setText("");
        wardCombo.setEnabled(true);
        groupCombo.setEnabled(true);
        conditionText.setText("");
        reactionYesRadio.setSelected(false);
        reactionNoRadio.setSelected(false);
        symptomText.setText("");
        CollectorText.setText("");
        dateChooser.setEnabled(true);
        addTime.setEnabled(true);
        priorityCombo.setEnabled(true);
        recievedDateChooser.setEnabled(true);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Clear the entries?", "Clear", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            clear();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void symptomTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symptomTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symptomTextActionPerformed

    private void reactionYesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reactionYesRadioActionPerformed
        if (reactionYesRadio.isSelected()) {
            symptomLabel.setEnabled(true);
            symptomText.setEnabled(true);
            symptomText.requestFocus(true);
        }
    }//GEN-LAST:event_reactionYesRadioActionPerformed

    private void reactionNoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reactionNoRadioActionPerformed
        if (reactionNoRadio.isSelected()) {
            symptomLabel.setEnabled(false);
            symptomText.setEnabled(false);
            CollectorText.requestFocus(true);
        }
    }//GEN-LAST:event_reactionNoRadioActionPerformed

    private void femaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioActionPerformed
        weightText.requestFocus(true);
    }//GEN-LAST:event_femaleRadioActionPerformed

    private void maleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioActionPerformed
        weightText.requestFocus(true);
    }//GEN-LAST:event_maleRadioActionPerformed

    private void hospitalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalComboActionPerformed
        bhtText.requestFocus(true);
    }//GEN-LAST:event_hospitalComboActionPerformed

    private void wardComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardComboActionPerformed
        groupCombo.requestFocus(true);
    }//GEN-LAST:event_wardComboActionPerformed

    private void ageTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE) || c == java.awt.event.KeyEvent.VK_DELETE) {
            evt.consume();
        }

        c = evt.getKeyChar();
        if (nameText.getText().length() < 10) {
            if (c == java.awt.event.KeyEvent.VK_ENTER) {
                maleRadio.requestFocus(true);
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_ageTextKeyTyped

    private void weightTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weightTextKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE) || c == java.awt.event.KeyEvent.VK_DELETE) {
            evt.consume();
        }
        c = evt.getKeyChar();
        if (nameText.getText().length() < 4) {
            if (c == java.awt.event.KeyEvent.VK_ENTER) {
                hospitalCombo.requestFocus(true);
            }
        } else {
            evt.consume();
        }

    }//GEN-LAST:event_weightTextKeyTyped

    private void requestIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestIDTextActionPerformed

    }//GEN-LAST:event_requestIDTextActionPerformed

    private void requestIDTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_requestIDTextKeyTyped
        char c = evt.getKeyChar();
        if (requestIDText.getText().length() < 10) {
            if (c == java.awt.event.KeyEvent.VK_ENTER) {
                nameText.requestFocus(true);
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_requestIDTextKeyTyped

    private void nameTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyTyped
        char c = evt.getKeyChar();
        if (nameText.getText().length() < 70) {
            if (c == java.awt.event.KeyEvent.VK_ENTER) {
                ageText.requestFocus(true);
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_nameTextKeyTyped

    private void ageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextActionPerformed

    private void weightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTextActionPerformed

    private void bhtTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bhtTextKeyTyped
        char c = evt.getKeyChar();
        if (nameText.getText().length() < 20) {
            if (c == java.awt.event.KeyEvent.VK_ENTER) {
                wardCombo.requestFocus(true);
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_bhtTextKeyTyped

    private void groupComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupComboActionPerformed
        conditionText.requestFocus(true);
    }//GEN-LAST:event_groupComboActionPerformed

    private void conditionTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conditionTextKeyTyped
        char c = evt.getKeyChar();
        if (nameText.getText().length() < 100) {
            if (c == java.awt.event.KeyEvent.VK_ENTER) {
                reactionYesRadio.requestFocus(true);
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_conditionTextKeyTyped

    private void symptomTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_symptomTextKeyTyped
        char c = evt.getKeyChar();
        if (nameText.getText().length() < 150) {
            if (c == java.awt.event.KeyEvent.VK_ENTER) {
                CollectorText.requestFocus(true);
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_symptomTextKeyTyped

    private void CollectorTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CollectorTextKeyTyped
        char c = evt.getKeyChar();
        if (c == java.awt.event.KeyEvent.VK_ENTER) {
            dateChooser.requestFocus(true);
        }
    }//GEN-LAST:event_CollectorTextKeyTyped

    private void CollectorTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollectorTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CollectorTextActionPerformed

    private void dateChooserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateChooserKeyReleased
        recievedDateChooser.requestFocus(true);
    }//GEN-LAST:event_dateChooserKeyReleased

    private void recievedDateChooserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recievedDateChooserKeyReleased
        addTime.requestFocus(true);
    }//GEN-LAST:event_recievedDateChooserKeyReleased

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void bhtTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhtTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bhtTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CollectorText;
    private javax.swing.JButton add;
    private lu.tudor.santec.jtimechooser.JTimeChooser addTime;
    private javax.swing.JTextField ageText;
    private javax.swing.JTextField bhtText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JTextField conditionText;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JComboBox groupCombo;
    private javax.swing.JComboBox hospitalCombo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField nameText;
    private javax.swing.JComboBox priorityCombo;
    private javax.swing.JRadioButton reactionNoRadio;
    private javax.swing.JRadioButton reactionYesRadio;
    private com.toedter.calendar.JDateChooser recievedDateChooser;
    private javax.swing.JTextField requestIDText;
    private javax.swing.JLabel symptomLabel;
    private javax.swing.JTextField symptomText;
    private javax.swing.JComboBox wardCombo;
    private javax.swing.JTextField weightText;
    // End of variables declaration//GEN-END:variables

}
